id: 00b6d9ad-70e5-4521-875a-510b506f75db
version: 45
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Software Select
description: Checks to validate that a version (if provided) is valid for upgrade
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 54cde091-ce3b-4d67-8d59-edf12ee71149
    type: start
    task:
      id: 54cde091-ce3b-4d67-8d59-edf12ee71149
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 456,
          "y": -233
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 3dfa6d71-a5c4-4b79-aaae-b519b126da0c
    type: regular
    task:
      id: 3dfa6d71-a5c4-4b79-aaae-b519b126da0c
      version: -1
      name: Filter available Images
      description: Given a table containing installed ("current") PAN-OS Software
        images, compare with available to determine
      scriptName: FilterAvailableSoftwareImages
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      available_images:
        complex:
          root: PANOS.SoftwareVersions.Summary
          filters:
          - - operator: isFalse
              left:
                value:
                  simple: PANOS.SoftwareVersions.Summary.current
                iscontext: true
      installed_images:
        complex:
          root: PANOS.SoftwareVersions.Summary
          filters:
          - - operator: isTrue
              left:
                value:
                  simple: PANOS.SoftwareVersions.Summary.current
                iscontext: true
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 456,
          "y": 221
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: PAN-OS Network Operations - Upgrade Panorama Version
      output:
        complex:
          root: FilteredSoftwareVersions.Result
          accessor: version
          transformers:
          - operator: join
            args:
              separator:
                value:
                  simple: ', '
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: bbc0dd07-ad9e-4a9c-9f67-ef7307835dab
    type: condition
    task:
      id: bbc0dd07-ad9e-4a9c-9f67-ef7307835dab
      version: -1
      name: Do we have a target version already? - should also check yes and valid
      description: Check for target version.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      yes - and valid:
      - "11"
    separatecontext: false
    conditions:
    - label: yes - and valid
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.TargetVersion
            iscontext: true
      - - operator: inList
          left:
            value:
              simple: inputs.TargetVersion
            iscontext: true
          right:
            value:
              simple: FilteredSoftwareVersions.Result.version
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 456,
          "y": 394
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 4912dcf3-f199-4a9d-a026-53be37b930e9
    type: collection
    task:
      id: 4912dcf3-f199-4a9d-a026-53be37b930e9
      version: -1
      name: Target Version and Upgrade information Questionnaire
      description: Collects the upgrade details from the user.
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 759,
          "y": 640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to: null
      subject: null
      body:
        simple: Please complete the following survey to proceed with the platform
          upgrade process.
      methods: []
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          complex:
            root: FilteredSoftwareVersions.Result
            accessor: current_image
            transformers:
            - operator: uniq
            - operator: concat
              args:
                prefix:
                  value:
                    simple: ' - Select Target Software Version.  Current is **'
                suffix:
                  value:
                    simple: '**'
            - operator: concat
              args:
                prefix:
                  value:
                    simple: FilteredSoftwareVersions.Result.[0].hostid
                  iscontext: true
                suffix: {}
        required: true
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options: []
        optionsarg:
        - complex:
            root: FilteredSoftwareVersions.Result
            accessor: version
            transformers:
            - operator: sort
              args:
                descending: {}
        - {}
        fieldassociated: ""
        placeholder: ""
        tooltip: The possible versions to upgrade.
        readonly: false
      title: Upgrade Questions
      description: |-
        ## Overview
        Please specify the target image versions for Panorama or the Firewalls.


        ## Image Upgrade Restrictions
        Note that the associated image list is based on the following limitations and is NOT the complete list of available PAN-OS software;

         * Image must not be > 1 Major release ahead
         * Image must not be > 1 Minor release ahead
         * Image must not be a combination of the two above

        **In the event of a large gap between firewall versions within the environment, the upgrade process will require a manual selection for each firewall that can't be directly upgraded to the target version.**
      sender: Your SOC team
      expired: false
      totalanswers: 0
    formDisplay:
      headerbackgroundcolor: ""
      headerfontcolor: ""
      sender: ""
      bodybackgroundcolor: ""
      bodyfontcolor: ""
      submitbuttonbackgroundcolor: ""
      submitbuttonfontcolor: ""
      submittext: ""
      isexternalrtl: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 00fc0151-bec3-4b29-bc7e-58676649902b
    type: regular
    task:
      id: 00fc0151-bec3-4b29-bc7e-58676649902b
      version: -1
      name: Set Target Version
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      key:
        simple: TargetVersion
      value:
        simple: ${Upgrade Questions.Answers.0}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 756,
          "y": 799
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: a7fe29ca-8064-4c2c-89ee-0e6c46c52885
    type: regular
    task:
      id: a7fe29ca-8064-4c2c-89ee-0e6c46c52885
      version: -1
      name: Set Target Version
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      key:
        simple: TargetVersion
      value:
        simple: ${inputs.TargetVersion}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 245,
          "y": 626
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 36ec56a1-d703-4afd-87c0-2a6f77fdd42b
    type: title
    task:
      id: 36ec56a1-d703-4afd-87c0-2a6f77fdd42b
      version: -1
      name: DONE
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 456,
          "y": 1137
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 5c698adf-9f9e-42ed-ac03-fd2b5a36a531
    type: regular
    task:
      id: 5c698adf-9f9e-42ed-ac03-fd2b5a36a531
      version: -1
      name: Get Software Images
      description: Checks the devices for software that is available to be installed.
      script: Panorama|||pan-os-platform-get-available-software
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.TargetDevice}
      using:
        simple: ${inputs.PanoramaInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 456,
          "y": 54
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 8f0b78af-cbb6-4133-8cef-7e6b4456cc41
    type: regular
    task:
      id: 8f0b78af-cbb6-4133-8cef-7e6b4456cc41
      version: -1
      name: Set Upgrade Path
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      key:
        simple: UpgradePath
      value:
        complex:
          root: FilteredSoftwareVersions.Result
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: FilteredSoftwareVersions.Result.version
                iscontext: true
              right:
                value:
                  simple: ${TargetVersion}
                iscontext: true
              ignorecase: true
          accessor: upgrade_path
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 456,
          "y": 966
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 085449b0-2998-481c-88bb-fce6a73309ef
    type: regular
    task:
      id: 085449b0-2998-481c-88bb-fce6a73309ef
      version: -1
      name: Clear Context for Looping
      description: "Delete field from context.\n\nThis automation runs using the default
        Limited User role, unless you explicitly change the permissions.\nFor more
        information, see the section about permissions here:\n- For Cortex XSOAR 6
        see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      all:
        simple: "yes"
      subplaybook:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 456.25,
          "y": -93.125
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "3_11_yes - and valid": 0.35,
      "3_5_#default#": 0.37
    },
    "paper": {
      "dimensions": {
        "height": 1430,
        "width": 894,
        "x": 245,
        "y": -233
      }
    }
  }
inputs:
- key: TargetVersion
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: TargetDevice
  value: {}
  required: true
  description: ""
  playbookInputQuery: null
- key: PanoramaInstance
  value: {}
  required: true
  description: ""
  playbookInputQuery: null
inputSections:
- inputs:
  - TargetVersion
  - TargetDevice
  - PanoramaInstance
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs:
  - TargetVersion
  - UpgradePath
  name: General (Outputs group)
  description: Generic group for outputs
outputs:
- contextPath: TargetVersion
  description: The target software version to upgrade
  type: unknown
- contextPath: UpgradePath
  description: The upgrade path to reach the target version
  type: unknown
quiet: true
dirtyInputs: true
