id: PAN-OS Network Operations - Start Device Upgrades
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Start Device Upgrades
description: |-
  This playbook is used by the Domain Upgrade playbook to start (either manually or automatically) groups of Device Upgrade incidents.

  It works by first retrieving the administrative domains/device-groups that have upgrades pending, then marking the pause tasks within them complete in batches.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1dc3342b-ef56-42f5-8373-9b0e68a44cf8
    type: start
    task:
      id: 1dc3342b-ef56-42f5-8373-9b0e68a44cf8
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: ceb31d59-77c9-4666-8770-f0e9461466fe
    type: condition
    task:
      id: ceb31d59-77c9-4666-8770-f0e9461466fe
      version: -1
      name: Is auto-upgrade enabled?
      description: Check for automatic upgrade switch
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isTrue
          left:
            value:
              simple: inputs.Automatically Upgrade
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 2394bb87-2894-4b93-82e4-d8dee99db956
    type: regular
    task:
      id: 2394bb87-2894-4b93-82e4-d8dee99db956
      version: -1
      name: Start device upgrades
      description: commands.local.cmd.task.complete
      script: Builtin|||taskComplete
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      id:
        simple: start-upgrade
      incidentId:
        complex:
          root: inputs.incident_ids
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: c32fa420-5b2d-4849-8fc8-0caee986a376
    type: condition
    task:
      id: c32fa420-5b2d-4849-8fc8-0caee986a376
      version: -1
      name: Begin Upgrades
      description: |-
        #### Do you want to start upgrading all devices?

        This will **start upgrades** on all of the devices, which may result in an **interruption to network traffic.**
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "No":
      - "4"
      "Yes":
      - "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 720,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to: null
      subject: null
      body:
        simple: |-
          Do you want to start all device upgrades?

          This wil start upgrades on the following devices;

          ${incident.panosnetworkoperationspanoramaupgradelist}

          ${incident.panosnetworkoperationsfirewallupgradelist}
      methods: []
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
      replyOptions:
      - "Yes"
      - "No"
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 72ed54d5-46c2-4a15-8612-05edbae8f54c
    type: title
    task:
      id: 72ed54d5-46c2-4a15-8612-05edbae8f54c
      version: -1
      name: Finish
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 755,
        "width": 650,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: Automatically Upgrade
  value:
    simple: ${incident.panosnetworkoperationsautomaticupgradeswitch}
  required: false
  description: If set to true, will automatically start all device ugprades.
  playbookInputQuery: null
- key: incident_ids
  value:
    simple: ${CreatedIncidentID}
  required: false
  description: List of incident IDs corresponding to device upgrade incidents to start.
  playbookInputQuery: null
outputs: []
