id: PAN-OS Network Operations - Upgrade Assurance - First Snapshot
version: 20
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Upgrade Assurance - First Snapshot
description: Meant to be executed before upgrading a firewall.  Will run a readiness
  test and take a snapshot.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: dc7b59be-21c9-4c80-8b9a-4476f6ba923e
    type: start
    task:
      id: dc7b59be-21c9-4c80-8b9a-4476f6ba923e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -70
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 08025212-f30a-46fb-b975-eac16bb86fcd
    type: regular
    task:
      id: 08025212-f30a-46fb-b975-eac16bb86fcd
      version: -1
      name: Run Readiness Tests
      description: Runs checks to confirm a PAN-OS firewall is ready to be upgraded.
      script: PAN_OS_Upgrade_Assurance|||pan-os-assurance-run-readiness-checks
      type: regular
      iscommand: true
      brand: PAN_OS_Upgrade_Assurance
    nexttasks:
      '#none#':
      - "2"
      - "13"
    scriptarguments:
      arp_entry_exists:
        simple: ${alert.checkarpentryexists}
      candidate_version:
        simple: ${inputs.target_version}
      check_list:
        simple: ${alert.readinesschecklist}
      check_session_exists:
        simple: ${alert.checksessionexists}
      firewall_serial:
        simple: ${inputs.target}
      min_content_version:
        simple: ${alert.minimumcontentversion}
      using:
        simple: ${inputs.AssuranceInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: Readiness Check Result
      output:
        complex:
          root: FirewallAssurance
          accessor: ReadinessCheckResults
          transformers:
          - operator: ConvertKeysToTableFieldFormat
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 3e473922-d109-439b-9e6b-d0450c2fa1e1
    type: condition
    task:
      id: 3e473922-d109-439b-9e6b-d0450c2fa1e1
      version: -1
      name: Did we get failed tests?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: alert.readinesscheckresult.state
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: alert.readinesscheckresult.state
                      iscontext: true
                    right:
                      value:
                        simple: "false"
                    ignorecase: true
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: a20b19f9-ec48-4128-ac3c-b93718855018
    type: collection
    task:
      id: a20b19f9-ec48-4128-ac3c-b93718855018
      version: -1
      name: Failed Readiness Test Confirmation
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: ${alert.owner}
      subject:
        simple: Upgrade Readiness Checks failed on ${inputs.target}
      body:
        simple: "The assurance process failed on the device ${inputs.target}.\n\nPlease
          validate the test result and choose whether to proceed or abort the assurance
          process. "
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: |-
            ### Do you want to continue?
            *Choosing Yes will continue with the upgrade assurance process, and if no other issues are present, the upgrade process itself.*
        required: true
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      title: Failed Readiness Test Confirmation
      description: The assurance process identified issues that might prevent the
        software upgrade from starting. Please confirm whether to proceed or abort
        the assurance process.
      sender: Your SOC team
      expired: false
      totalanswers: 0
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: f9003837-5d6c-4a4b-a4e7-fc0aa7c6b290
    type: condition
    task:
      id: f9003837-5d6c-4a4b-a4e7-fc0aa7c6b290
      version: -1
      name: Continue?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Failed Readiness Test Confirmation.Answers.0
            iscontext: true
          right:
            value:
              simple: "Yes"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 940
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: af0babe8-1947-49b6-982e-1e72693de600
    type: regular
    task:
      id: af0babe8-1947-49b6-982e-1e72693de600
      version: -1
      name: Take the first device snapshot
      description: Takes a snapshot of the operational state of the system.
      script: PAN_OS_Upgrade_Assurance|||pan-os-assurance-run-snapshot
      type: regular
      iscommand: true
      brand: PAN_OS_Upgrade_Assurance
    scriptarguments:
      check_list:
        simple: ${alert.snapshotchecklist}
      firewall_serial:
        simple: ${inputs.target}
      snapshot_name:
        simple: first_snapshot
      using:
        simple: ${inputs.AssuranceInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 6fa989d3-88a2-485e-8573-e10c0bed0b5d
    type: regular
    task:
      id: 6fa989d3-88a2-485e-8573-e10c0bed0b5d
      version: -1
      name: Aborted process.
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      details:
        simple: Assurance testing aborted.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 1260
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: ffa0511a-395c-4b30-8fc3-fa06132eec6b
    type: title
    task:
      id: ffa0511a-395c-4b30-8fc3-fa06132eec6b
      version: -1
      name: "YES"
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 88ef7f78-8898-42d3-80e6-756608c10f46
    type: title
    task:
      id: 88ef7f78-8898-42d3-80e6-756608c10f46
      version: -1
      name: "No"
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 4f0437a2-984b-42c1-99e0-fa43bbb0368c
    type: regular
    task:
      id: 4f0437a2-984b-42c1-99e0-fa43bbb0368c
      version: -1
      name: Update Report
      description: This script takes the results from readiness checks and/or snapshot
        comparison checks and appends the results in a report format
      scriptName: CreateUpgradeReport
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      readiness_results:
        simple: ${FirewallAssurance.ReadinessCheckResults}
      stage:
        simple: PreUpgrade
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 20,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: Upgrade Assurance Report
      output:
        simple: ${UpgradeReport}
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 2b485afe-991d-4b03-8871-a85c2cac2f35
    type: regular
    task:
      id: 2b485afe-991d-4b03-8871-a85c2cac2f35
      version: -1
      name: Clear Context for Looping
      description: "Delete field from context.\n\nThis automation runs using the default
        Limited User role, unless you explicitly change the permissions.\nFor more
        information, see the section about permissions here:\n- For Cortex XSOAR 6
        see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      subplaybook:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 9ab2fd45-78ad-472a-88ed-a745bd7411ab
    type: regular
    task:
      id: 9ab2fd45-78ad-472a-88ed-a745bd7411ab
      version: -1
      name: Manual Task to Abort
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 1440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1580,
        "width": 1220,
        "x": 20,
        "y": -70
      }
    }
  }
inputs:
- key: target
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: target_version
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: AssuranceInstance
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
inputSections:
- inputs:
  - target
  - target_version
  - AssuranceInstance
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs:
  - File.EntryID
  name: General (Outputs group)
  description: Generic group for outputs
outputs:
- contextPath: File.EntryID
  description: The EntryID of the report file.
quiet: true
dirtyInputs: true
