id: PAN-OS Network Operations - Device Upgrade
version: 15
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Device Upgrade
description: Upgrades a single or HA pair of PAN-OS firewalls.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a4331e6d-aa19-4373-88b5-7bf54c96bb0d
    type: start
    task:
      id: a4331e6d-aa19-4373-88b5-7bf54c96bb0d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "68"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "48":
    id: "48"
    taskid: 932ddd71-494e-403b-8fe7-8cfe7b7815e9
    type: regular
    task:
      id: 932ddd71-494e-403b-8fe7-8cfe7b7815e9
      version: -1
      name: Set Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "63"
    scriptarguments:
      name:
        simple: PAN-OS Upgrade - ${inputs.target_device}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "61":
    id: "61"
    taskid: e3032a01-2a00-405b-86de-b2d8abbb21aa
    type: title
    task:
      id: e3032a01-2a00-405b-86de-b2d8abbb21aa
      version: -1
      name: Complete!
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 1570
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "62":
    id: "62"
    taskid: 7c481649-e312-41d0-be9c-c5d01cc4c4be
    type: playbook
    task:
      id: 7c481649-e312-41d0-be9c-c5d01cc4c4be
      version: -1
      name: PAN-OS Network Operations - Device Upgrade Loop
      description: Upgrades a single or HA pair of PAN-OS firewalls, supports running
        as a subplaybook and be looped over to complete an entire upgrade path.
      playbookName: PAN-OS Network Operations - Device Upgrade Loop
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "64"
    scriptarguments:
      AssuranceInstance:
        simple: ${AssuranceInstance}
      PanoramaInstance:
        simple: ${PanoramaInstance}
      autoclose_incident:
        simple: "true"
      reset_ha_topology:
        simple: "false"
      target_device:
        simple: ${NGFWDevices}
      target_version:
        simple: ${UpgradePath}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "63":
    id: "63"
    taskid: c59123ff-16ca-4b80-a50f-f78ce2e3568b
    type: playbook
    task:
      id: c59123ff-16ca-4b80-a50f-f78ce2e3568b
      version: -1
      name: PAN-OS Network Operations - Software Select
      description: Checks to validate that a version (if provided) is valid for upgrade
      playbookName: PAN-OS Network Operations - Software Select
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "62"
    scriptarguments:
      PanoramaInstance:
        simple: ${PanoramaInstance}
      TargetDevice:
        simple: ${NGFWDevices}
      TargetVersion:
        simple: ${alert.panosnetworkoperationstargetngfwsoftware}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 890
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "64":
    id: "64"
    taskid: da879fb7-157c-47a1-9b89-2105f09ff467
    type: condition
    task:
      id: da879fb7-157c-47a1-9b89-2105f09ff467
      version: -1
      name: Autoclose alert?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "61"
      "yes":
      - "65"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.autoclose_incident
            iscontext: true
          right:
            value:
              simple: "true"
          ignorecase: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "65":
    id: "65"
    taskid: da88c860-5ad3-43c5-8108-24f2f0f081a2
    type: regular
    task:
      id: da88c860-5ad3-43c5-8108-24f2f0f081a2
      version: -1
      name: Close alert- Complete
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "61"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 1400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "66":
    id: "66"
    taskid: eef6bdc7-b452-41f0-85bc-9f386f8c7b13
    type: playbook
    task:
      id: eef6bdc7-b452-41f0-85bc-9f386f8c7b13
      version: -1
      name: PAN-OS Network Operations - Query Devices
      description: |-
        This queries XQL (and prompts for the XQL if not present) to identify firewalls and panoramas to upgrade.

        It outputs:
        * necessary instance names for the Panorama and UpgradeAssurance integration instances
        * list of firewall devices to be upgraded (from XQL query)
        * list of panoramas to be ugprades (from XQL query)
        * any errors that are found
      playbookName: PAN-OS Network Operations - Query Devices
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "67"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "67":
    id: "67"
    taskid: a50b0eb4-0d58-4f18-82c3-253f3b9d609a
    type: condition
    task:
      id: a50b0eb4-0d58-4f18-82c3-253f3b9d609a
      version: -1
      name: Any Errors from Query?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "48"
      "yes":
      - "65"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Errors
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 550
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "68":
    id: "68"
    taskid: b4814459-0f1e-4f10-8c2e-49b05771d892
    type: regular
    task:
      id: b4814459-0f1e-4f10-8c2e-49b05771d892
      version: -1
      name: Delete context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "66"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1580,
        "width": 670.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
inputSections:
- inputs: []
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs: []
  name: General (Outputs group)
  description: Generic group for outputs
outputs: []
dirtyInputs: true
