id: 7409a83d-eab4-4acd-8b93-a4abc6a038e4
version: 4
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Get HA Pair Status
description: Determines which device in a HA pair is active or passive, and if the
  pair is an active-passive or active-active mode.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: f26cbc58-60a2-4730-80f2-e205fa840672
    type: start
    task:
      id: f26cbc58-60a2-4730-80f2-e205fa840672
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 3027c8f3-621a-483f-8598-a8e2b1975c1a
    type: regular
    task:
      id: 3027c8f3-621a-483f-8598-a8e2b1975c1a
      version: -1
      name: Get HA state
      description: Gets the HA state and associated details from the given device
        and any other details.
      script: '|||pan-os-platform-get-ha-state'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      target:
        simple: ${inputs.target}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 784f87f3-d556-426d-846e-3d3b128cad61
    type: condition
    task:
      id: 784f87f3-d556-426d-846e-3d3b128cad61
      version: -1
      name: Is there a peer?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: PANOS.HAState.peer
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 1d913ab2-1a77-4664-84df-19f2a3ea35aa
    type: regular
    task:
      id: 1d913ab2-1a77-4664-84df-19f2a3ea35aa
      version: -1
      name: Get Peer HA State
      description: Gets the HA state and associated details from the given device
        and any other details.
      script: '|||pan-os-platform-get-ha-state'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
      - "6"
    scriptarguments:
      target:
        simple: ${PANOS.HAState.peer}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 520
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: c0251ee7-8d3b-4d99-8414-319b3c9993bc
    type: title
    task:
      id: c0251ee7-8d3b-4d99-8414-319b3c9993bc
      version: -1
      name: Finish - No HA
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1070,
          "y": 920
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: e8cf049d-d51b-4713-8213-12108479d60c
    type: regular
    task:
      id: e8cf049d-d51b-4713-8213-12108479d60c
      version: -1
      name: Set Active Peer
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: ActiveDevice
      value:
        complex:
          root: PANOS.HAState
          filters:
          - - operator: isTrue
              left:
                value:
                  simple: PANOS.HAState.active
                iscontext: true
          accessor: hostid
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 250,
          "y": 700
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 92f4a105-7b90-4eac-899a-7b717fc621bf
    type: regular
    task:
      id: 92f4a105-7b90-4eac-899a-7b717fc621bf
      version: -1
      name: Set Passive Peer
      description: |-
        Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: PassiveDevice
      value:
        complex:
          root: PANOS.HAState
          filters:
          - - operator: isFalse
              left:
                value:
                  simple: PANOS.HAState.active
                iscontext: true
          - - operator: isEqualString
              left:
                value:
                  simple: PANOS.HAState.status
                iscontext: true
              right:
                value:
                  simple: passive
          accessor: hostid
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 660,
          "y": 700
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: b8b3a487-e17a-42ef-8678-1d754343bcc7
    type: title
    task:
      id: b8b3a487-e17a-42ef-8678-1d754343bcc7
      version: -1
      name: Finish HA Discovery
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 935,
        "width": 1200,
        "x": 250,
        "y": 50
      }
    }
  }
inputs:
- key: target
  value: {}
  required: false
  description: Target firewall
  playbookInputQuery: null
outputs:
- contextPath: ActiveDevice
  description: The active firewall
  type: string
- contextPath: PassiveDevice
  description: The passive firewall - may be empty.
  type: string
