id: e68255ec-01a8-40a5-82d4-93b104eeb851
version: 4
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Filter and Select Available Software Images
description: Requests the available software images from a firewall, filters them, then prompts the user to select the version.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 648f4e35-86d3-4e18-864f-e2eff10611f0
    type: start
    task:
      id: 648f4e35-86d3-4e18-864f-e2eff10611f0
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -10
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: bf77e034-bc6b-4490-8737-79a982f91bcc
    type: collection
    task:
      id: bf77e034-bc6b-4490-8737-79a982f91bcc
      version: -1
      name: Collect Target Version
      description: If a target version wasn't given, ask the user for the version to upgrade to.
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
      subject:
      body:
        simple: Specify the final target version of firewall software.
      methods: []
      format: ""
      bcc:
      cc:
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: |-
            ### Choose the target version from the list of available versions.

            **Important: Specifying a version more than one feature release ahead of the current release will result in multiple upgrades and device reboots to complete all intermediary update steps**
        required: false
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options: []
        optionsarg:
        - simple: ${FilteredSoftwareVersions.Result.version}
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      title: Specify Target Software Version
      description: ""
      sender: ""
      expired: false
      totalanswers: 0
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 6b46334e-6185-45f5-8949-c15ef73c0230
    type: regular
    task:
      id: 6b46334e-6185-45f5-8949-c15ef73c0230
      version: -1
      name: Get Available software Images
      description: Checks the devices for software that is available to be installed.
      script: '|||pan-os-platform-get-available-software'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      target:
        simple: ${inputs.target}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 24e1a72d-a3f2-4c1a-856f-70c1ec206ba2
    type: regular
    task:
      id: 24e1a72d-a3f2-4c1a-856f-70c1ec206ba2
      version: -1
      name: Filter the available software images
      description: Given a table containing installed ("current") PAN-OS Software images, compare with available to determine
      scriptName: FilterAvailableSoftwareImages
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      available_images:
        simple: ${PANOS.SoftwareVersions.Summary}
      installed_images:
        complex:
          root: PANOS.SoftwareVersions.Summary
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: PANOS.SoftwareVersions.Summary.current
                iscontext: true
              right:
                value:
                  simple: "true"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 376683d7-57d8-47ee-88c5-9cdf352e2efb
    type: regular
    task:
      id: 376683d7-57d8-47ee-88c5-9cdf352e2efb
      version: -1
      name: Set the relevant incident fields
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      nextupgradeversion:
        complex:
          root: FilteredSoftwareVersions.Result
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: FilteredSoftwareVersions.Result.version
                iscontext: true
              right:
                value:
                  simple: incident.panosnetworkoperationsupgradetargetversion
                iscontext: true
          accessor: next_upgrade_version
      upgradepath:
        complex:
          root: FilteredSoftwareVersions.Result
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: FilteredSoftwareVersions.Result.version
                iscontext: true
              right:
                value:
                  simple: incident.panosnetworkoperationsupgradetargetversion
                iscontext: true
          accessor: upgrade_path
          transformers:
          - operator: join
            args:
              separator:
                value:
                  simple: ', '
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 0dfb1be3-f002-4c7b-8c40-89ebac225b7c
    type: condition
    task:
      id: 0dfb1be3-f002-4c7b-8c40-89ebac225b7c
      version: -1
      name: Do we have a Final target version already?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "1"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: incident.panosnetworkoperationsupgradetargetversion
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 480
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 6c883ad1-7937-44cd-874b-b9bf8fa7b6db
    type: regular
    task:
      id: 6c883ad1-7937-44cd-874b-b9bf8fa7b6db
      version: -1
      name: Set Target Version
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      panosnetworkoperationsupgradetargetversion:
        simple: ${Specify Target Software Version.Answers.0}
      releasenotes:
        complex:
          root: FilteredSoftwareVersions.Result
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: FilteredSoftwareVersions.Result.version
                iscontext: true
              right:
                value:
                  simple: Specify Target Software Version.Answers.0
                iscontext: true
          accessor: release_notes
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 810
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1105,
        "width": 380,
        "x": 450,
        "y": -10
      }
    }
  }
inputs:
- key: target
  value: {}
  required: true
  description: The target firewall.
  playbookInputQuery:
outputs: []
