id: PAN-OS Network Operations - Download Software
version: 4
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Download Software
description: Download PAN-OS System software.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ad09c3c6-638f-4eea-8273-87c0d4892e68
    type: start
    task:
      id: ad09c3c6-638f-4eea-8273-87c0d4892e68
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -510
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: f5a1c2d1-684c-41c8-8f07-93e28058cca2
    type: regular
    task:
      id: f5a1c2d1-684c-41c8-8f07-93e28058cca2
      version: -1
      name: Download the Software Version
      description: Download The provided software version onto the device.
      script: '|||pan-os-platform-download-software'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      retry-count:
        simple: "5"
      retry-interval:
        simple: "60"
      version:
        simple: ${inputs.target_version}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -225
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 69e93e72-add1-42b3-8809-4be92a6c34c3
    type: regular
    task:
      id: 69e93e72-add1-42b3-8809-4be92a6c34c3
      version: -1
      name: Get Jobs
      description: Get all the jobs from the devices in the environment.
      script: '|||pan-os-platform-get-jobs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      device_filter_string:
        simple: ${PANOS.DownloadStatus.Summary.hostid}
      ignore-outputs:
        simple: "false"
      job_type:
        simple: Downld
      status:
        simple: ACT
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: d156b92b-68bb-4453-89eb-a38b54fe8137
    type: playbook
    task:
      id: d156b92b-68bb-4453-89eb-a38b54fe8137
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: device_filter_string
      AdditionalPollingCommandArgValues:
        simple: ${inputs.target}
      Ids:
        complex:
          root: PANOS.JobStatus
          accessor: id
          transformers:
          - operator: LastArrayElement
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: id
      PollingCommandName:
        simple: pan-os-platform-get-jobs
      Timeout:
        simple: ${inputs.timeout}
      dt:
        simple: PANOS.JobStatus(val.status!=="FIN").id
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      scriptArguments:
        Ids:
          complex:
            root: PANOS.JobStatus
            accessor: id
            transformers:
            - operator: LastArrayElement
        Interval:
          simple: "1"
        PollingCommandArgName:
          simple: id
        PollingCommandName:
          simple: pan-os-platform-get-jobs
        Timeout:
          simple: "30"
        dt:
          simple: PANOS.JobStatus(val.status!=="FIN").id
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 440,
          "y": 670
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 957f2d08-9f72-40a7-8bca-be0c4caa748c
    type: regular
    task:
      id: 957f2d08-9f72-40a7-8bca-be0c4caa748c
      version: -1
      name: Get jobs again to check status
      description: Get all the jobs from the devices in the environment, or a single job when ID is specified.
      script: '|||pan-os-platform-get-jobs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      id:
        complex:
          root: PANOS.JobStatus
          accessor: id
          transformers:
          - operator: LastArrayElement
      target:
        simple: ${inputs.target}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 8cef80ab-041e-41bf-8637-c131fe05277a
    type: condition
    task:
      id: 8cef80ab-041e-41bf-8637-c131fe05277a
      version: -1
      name: Did it complete?
      description: True if the software download was successful
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.JobStatus.status
            iscontext: true
          right:
            value:
              simple: FIN
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.JobStatus.result
            iscontext: true
          right:
            value:
              simple: OK
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: d8f79fd7-07cc-44a4-8dc4-d68ce6651ef4
    type: title
    task:
      id: d8f79fd7-07cc-44a4-8dc4-d68ce6651ef4
      version: -1
      name: Finish
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: eaee8eac-cdb5-4fb7-8fdd-6d1720426ea4
    type: regular
    task:
      id: eaee8eac-cdb5-4fb7-8fdd-6d1720426ea4
      version: -1
      name: Fail message
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Download job failed.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 870,
          "y": 1165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 3cc87bcc-ebcb-4745-80d3-6cff9e7d3c16
    type: regular
    task:
      id: 3cc87bcc-ebcb-4745-80d3-6cff9e7d3c16
      version: -1
      name: Set Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      description:
        simple: Downloading Software Version ${inputs.target_version}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 5841bc40-03e6-46d4-8250-506c53689dd6
    type: regular
    task:
      id: 5841bc40-03e6-46d4-8250-506c53689dd6
      version: -1
      name: Wait for job to get processed
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      seconds:
        simple: "30"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: de8733e0-82ea-456a-8269-4ec786be894c
    type: condition
    task:
      id: de8733e0-82ea-456a-8269-4ec786be894c
      version: -1
      name: Did we get a job?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: PANOS.JobStatus.id
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 801f2478-3110-425d-8cc8-397b09fe4d80
    type: regular
    task:
      id: 801f2478-3110-425d-8cc8-397b09fe4d80
      version: -1
      name: Get Jobs
      description: Get all the jobs from the devices in the environment.
      script: '|||pan-os-platform-get-jobs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      device_filter_string:
        simple: ${PANOS.DownloadStatus.Summary.hostid}
      ignore-outputs:
        simple: "false"
      job_type:
        simple: Downld
      status:
        simple: ACT
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1770,
        "width": 850,
        "x": 440,
        "y": -510
      }
    }
  }
inputs:
- key: target
  value: {}
  required: false
  description: Target Firewall - Serial or IP address
  playbookInputQuery:
- key: target_version
  value: {}
  required: false
  description: Target Software Version to Download
  playbookInputQuery:
- key: timeout
  value:
    simple: "45"
  required: false
  description: Default max timeout value
  playbookInputQuery:
outputs: []
