id: PAN-OS Network Operations - Device Upgrade
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Device Upgrade
description: Upgrades a single or HA pair of PAN-OS firewalls.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: fb008732-7c81-4a29-8fac-685a8aecf189
    type: start
    task:
      id: fb008732-7c81-4a29-8fac-685a8aecf189
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "58"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 520,
          "y": -3250
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: e7c5d007-8784-4d42-8e9f-f528622c005f
    type: regular
    task:
      id: e7c5d007-8784-4d42-8e9f-f528622c005f
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 840,
          "y": -3090
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "40":
    id: "40"
    taskid: a5bd47cf-f2b0-43d5-8b49-7b8208a7b50a
    type: condition
    task:
      id: a5bd47cf-f2b0-43d5-8b49-7b8208a7b50a
      version: -1
      name: Do we have a parent incident?
      description: True if this incident was created by another incident.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "59"
      "yes":
      - "41"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: incident.panosnetworkoperationsparentincidentid
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 520,
          "y": -2550
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "41":
    id: "41"
    taskid: 864221e0-537c-46c9-8bb0-d845d109636b
    type: regular
    task:
      id: 864221e0-537c-46c9-8bb0-d845d109636b
      version: -1
      name: Link to parent
      description: commands.local.cmd.linkIncidents
      script: Builtin|||linkIncidents
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "59"
    scriptarguments:
      linkedIncidentIDs:
        simple: ${incident.panosnetworkoperationsparentincidentid}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 750,
          "y": -2350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "48":
    id: "48"
    taskid: 90456116-c413-4e73-8932-7230b603fae1
    type: regular
    task:
      id: 90456116-c413-4e73-8932-7230b603fae1
      version: -1
      name: Set Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "40"
    scriptarguments:
      description:
        simple: Awaiting Upgrade Confirmation
      name:
        simple: PAN-OS Upgrade - ${inputs.target_device}
      severity:
        simple: "0.5"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 520,
          "y": -2755
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "58":
    id: "58"
    taskid: 1565f349-af06-4822-8f78-a69736284bc8
    type: regular
    task:
      id: 1565f349-af06-4822-8f78-a69736284bc8
      version: -1
      name: Associate Device Indicator to this Incident
      description: Associates the device indicator to this incident; required when
        this is run as part of a batch upgrade
      script: Builtin|||associateIndicatorToIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "48"
    scriptarguments:
      incidentId:
        simple: ${incident.id}
      value:
        simple: ${inputs.target_device}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 520,
          "y": -2920
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "59":
    id: "59"
    taskid: fffa4566-2995-428e-8249-695ae6d6f06a
    type: playbook
    task:
      id: fffa4566-2995-428e-8249-695ae6d6f06a
      version: -1
      name: PAN-OS Network Operations - Filter and Select Available Software Images
      description: Requests the available software images from a firewall, filters
        them, then prompts the user to select the version.
      playbookName: PAN-OS Network Operations - Filter and Select Available Software
        Images
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "62"
    scriptarguments:
      target:
        simple: ${inputs.target_device}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 520,
          "y": -2140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "61":
    id: "61"
    taskid: 96d4c4a3-e5c5-4654-8d55-fc27e47f23aa
    type: title
    task:
      id: 96d4c4a3-e5c5-4654-8d55-fc27e47f23aa
      version: -1
      name: Complete!
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 520,
          "y": -1790
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "62":
    id: "62"
    taskid: 68c8e7e3-d834-402b-8fe2-e0de71a5d5ea
    type: playbook
    task:
      id: 68c8e7e3-d834-402b-8fe2-e0de71a5d5ea
      version: -1
      name: PAN-OS Network Operations - Device Upgrade Loop
      playbookName: PAN-OS Network Operations - Device Upgrade Loop
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "61"
    scriptarguments:
      peer_device:
        simple: ${incident.panosnetworkoperationsupgradepeerfirewall}
      target_device:
        simple: ${incident.panosnetworkoperationstarget}
      target_version:
        simple: ${incident.upgradepath}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": 520,
          "y": -1970
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1525,
        "width": 700,
        "x": 520,
        "y": -3250
      }
    }
  }
inputs:
- key: target_device
  value:
    simple: ${incident.panosnetworkoperationstarget}
  required: false
  description: Target Firewall for upgrade
  playbookInputQuery: null
- key: peer_device
  value:
    simple: ${incident.panosnetworkoperationsupgradepeerfirewall}
  required: false
  description: Peer firewall (if any)
  playbookInputQuery: null
- key: target_version
  value:
    simple: ${incident.panosnetworkoperationsupgradetargetversion}
  required: false
  description: Target version of upgrade
  playbookInputQuery: null
outputs: []
