id: PAN-OS Network Operations - Single Device Upgrade
version: 5
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Single Device Upgrade
description: Runs a complete upgrade process for a single device
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 91eefe42-28fe-4378-802a-e23dba37b3e1
    type: start
    task:
      id: 91eefe42-28fe-4378-802a-e23dba37b3e1
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "25"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -2110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 0db2708f-681f-4316-89be-ac62538313e5
    type: regular
    task:
      id: 0db2708f-681f-4316-89be-ac62538313e5
      version: -1
      name: Reboot the system
      description: Reboot the given host.
      script: '|||pan-os-platform-reboot'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      hostid:
        simple: ${inputs.target}
      target:
        simple: ${inputs.target}
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -65
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 2c3f9056-3964-47f0-84dd-868f12e294d9
    type: playbook
    task:
      id: 2c3f9056-3964-47f0-84dd-868f12e294d9
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      Ids:
        simple: ${inputs.target}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: target
      PollingCommandName:
        simple: pan-os-platform-get-system-status
      Timeout:
        simple: "60"
      dt:
        simple: PANOS.SystemStatus(!val.up).hostid
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      scriptArguments:
        AdditionalPollingCommandArgNames:
          simple: id
        AdditionalPollingCommandArgValues:
          complex:
            root: PANOS.JobStatus.Summary
            accessor: id
            transformers:
            - operator: FirstArrayElement
        Ids:
          complex:
            root: PANOS.JobStatus.Summary
            accessor: id
            transformers:
            - operator: FirstArrayElement
        Interval:
          simple: "1"
        PollingCommandArgName:
          simple: ids
        PollingCommandName:
          simple: pan-os-platform-get-jobs
        Timeout:
          simple: "10"
        dt:
          simple: PANOS.JobStatus.Result(val.status!=="FIN").id
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 450,
          "y": 300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 14a0d3de-2b94-41c9-8150-04caf462b276
    type: title
    task:
      id: 14a0d3de-2b94-41c9-8150-04caf462b276
      version: -1
      name: Finish
      description: Finish
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 825
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: daa9f32d-51c5-4a8b-866b-df82731115f5
    type: regular
    task:
      id: daa9f32d-51c5-4a8b-866b-df82731115f5
      version: -1
      name: Get System Info
      description: Gets information from all PAN-OS systems in the topology.
      script: '|||pan-os-platform-get-system-info'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: 8df2b9df-d39a-46be-85a8-d74d1a186222
    type: condition
    task:
      id: 8df2b9df-d39a-46be-85a8-d74d1a186222
      version: -1
      name: Check System running new version
      description: Checks whether the post-upgrade software version is correct.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "20"
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.ShowSystemInfo.Result.sw_version
            iscontext: true
          right:
            value:
              simple: inputs.target_version
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: 9f37d112-b591-49a6-896c-6eebd982c6b2
    type: regular
    task:
      id: 9f37d112-b591-49a6-896c-6eebd982c6b2
      version: -1
      name: Fail message
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Installation completed, reboot completed, but device still on old
          software version.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 810
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: 4fae2bf8-e8cf-4074-81c0-83ce539865fd
    type: regular
    task:
      id: 4fae2bf8-e8cf-4074-81c0-83ce539865fd
      version: -1
      name: Sleep to let device shutdown gracefully
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      seconds:
        simple: "25"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "22":
    id: "22"
    taskid: b7231fc3-6762-422e-8af1-676bfae38c06
    type: regular
    task:
      id: b7231fc3-6762-422e-8af1-676bfae38c06
      version: -1
      name: Get Available Software
      description: Check the devices for software that is available to be installed.
      script: '|||pan-os-platform-get-available-software'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "35"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1460
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "23":
    id: "23"
    taskid: a846ea9d-4cd6-40f1-8b8f-fb2b663ae69a
    type: condition
    task:
      id: a846ea9d-4cd6-40f1-8b8f-fb2b663ae69a
      version: -1
      name: Has the software already been downloaded?
      description: Checks if the upgrade software version is already downloaded onto
        the PAN-OS system.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "38"
      "yes":
      - "39"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              complex:
                root: PANOS.SoftwareVersions.Summary
                filters:
                - - operator: isTrue
                    left:
                      value:
                        simple: PANOS.SoftwareVersions.Summary.downloaded
                      iscontext: true
                accessor: version
            iscontext: true
          right:
            value:
              simple: inputs.target_version
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "24":
    id: "24"
    taskid: c8659392-64c4-496e-8d32-684166f7137d
    type: regular
    task:
      id: c8659392-64c4-496e-8d32-684166f7137d
      version: -1
      name: Save Device State
      description: Get the device state from the provided device.
      script: '|||pan-os-platform-get-device-state'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      hostid:
        simple: ${inputs.target}
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "25":
    id: "25"
    taskid: c1a50873-1b07-486b-8a23-b0bf9dad9515
    type: regular
    task:
      id: c1a50873-1b07-486b-8a23-b0bf9dad9515
      version: -1
      name: Get System Info
      description: Gets information from all PAN-OS systems in the topology.
      script: '|||pan-os-platform-get-system-info'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "26"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1980
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "26":
    id: "26"
    taskid: 231634fd-c635-4eb7-8376-b4e52c37a671
    type: condition
    task:
      id: 231634fd-c635-4eb7-8376-b4e52c37a671
      version: -1
      name: System Type
      description: Checks the system type.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "24"
      Panorama:
      - "22"
    separatecontext: false
    conditions:
    - label: Panorama
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.ShowSystemInfo.Summary.family
            iscontext: true
          right:
            value:
              simple: pc
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1830
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "27":
    id: "27"
    taskid: 90712f87-915f-4399-8a0d-d1735010e9a2
    type: condition
    task:
      id: 90712f87-915f-4399-8a0d-d1735010e9a2
      version: -1
      name: Is the base version of this image downloaded?
      description: True if the base version of the upgrade image is downloaded.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "37"
      "yes":
      - "23"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: in
          left:
            value:
              simple: BaseImage
            iscontext: true
          right:
            value:
              complex:
                root: PANOS.SoftwareVersions.Summary
                filters:
                - - operator: isTrue
                    left:
                      value:
                        simple: PANOS.SoftwareVersions.Summary.downloaded
                      iscontext: true
                accessor: version
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "35":
    id: "35"
    taskid: aadc01bb-b203-45a6-86e0-dd226ffdfdf6
    type: regular
    task:
      id: aadc01bb-b203-45a6-86e0-dd226ffdfdf6
      version: -1
      name: Set BASE Software Version
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      key:
        simple: BaseImage
      value:
        complex:
          root: inputs.target_version
          transformers:
          - operator: split
            args:
              delimiter:
                value:
                  simple: .
          - operator: slice
            args:
              from:
                value:
                  simple: "0"
              to:
                value:
                  simple: "2"
          - operator: join
            args:
              separator:
                value:
                  simple: .
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: ".0"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "37":
    id: "37"
    taskid: b63a7458-78a2-4c99-8290-542f5a55a065
    type: playbook
    task:
      id: b63a7458-78a2-4c99-8290-542f5a55a065
      version: -1
      name: PAN-OS Network Operations - Download Software
      description: Downloads the PAN-OS Software.
      playbookName: PAN-OS Network Operations - Download Software
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      target:
        simple: ${inputs.target}
      target_version:
        simple: ${BaseImage}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 690,
          "y": -930
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "38":
    id: "38"
    taskid: 671fdb2c-f704-4105-814a-81fb59c07de1
    type: playbook
    task:
      id: 671fdb2c-f704-4105-814a-81fb59c07de1
      version: -1
      name: PAN-OS Network Operations - Download Software
      description: Downloads the given software image.
      playbookName: PAN-OS Network Operations - Download Software
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "39"
    scriptarguments:
      target:
        simple: ${inputs.target}
      target_version:
        simple: ${inputs.target_version}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 690,
          "y": -565
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "39":
    id: "39"
    taskid: cb311a34-a34b-4623-870e-fb78275320f8
    type: playbook
    task:
      id: cb311a34-a34b-4623-870e-fb78275320f8
      version: -1
      name: PAN-OS Network Operations - Install Software
      description: Run the installation subplaybook.
      playbookName: PAN-OS Network Operations - Install Software
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "40"
    scriptarguments:
      target:
        simple: ${inputs.target}
      target_version:
        simple: ${inputs.target_version}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 450,
          "y": -375
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "40":
    id: "40"
    taskid: bc674cab-fb7f-44c0-8a1d-9b864f3f64c0
    type: regular
    task:
      id: bc674cab-fb7f-44c0-8a1d-9b864f3f64c0
      version: -1
      name: Set Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      description:
        simple: Rebooting System
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "23_38_#default#": 0.64
    },
    "paper": {
      "dimensions": {
        "height": 3015,
        "width": 840,
        "x": 450,
        "y": -2110
      }
    }
  }
inputs:
- key: target
  value: {}
  required: true
  description: Target firewall to upgrade
  playbookInputQuery: null
- key: target_version
  value: {}
  required: true
  description: Target version to upgrade to.
  playbookInputQuery: null
outputs: []
