id: PAN-OS Network Operations - Install Software
version: 7
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Install Software
description: Installs PAN-OS system software.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: bc8c80c2-3515-4d36-80e2-06a07a446e70
    type: start
    task:
      id: bc8c80c2-3515-4d36-80e2-06a07a446e70
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: e84e291b-b90b-42db-8710-296f6d4cb88d
    type: regular
    task:
      id: e84e291b-b90b-42db-8710-296f6d4cb88d
      version: -1
      name: Install the given software version
      description: Installs the given software version onto the device. Downloads
        the software first with panorama-download-panos-version.
      script: Panorama|||pan-os-platform-install-software
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      using:
        simple: ${inputs.PanoramaInstance}
      version:
        simple: ${inputs.target_version}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: a5674f65-c24e-4312-b998-a14fa16068d7
    type: regular
    task:
      id: a5674f65-c24e-4312-b998-a14fa16068d7
      version: -1
      name: Get Jobs
      description: Gets all the jobs from the devices in the environment, or a single
        job when the ID is specified.
      script: Panorama|||pan-os-platform-get-jobs
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      job_type:
        simple: SWInstall
      status:
        simple: ACT
      using:
        simple: ${inputs.PanoramaInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: ecdbf6bf-4f85-4d1e-9752-f1ea454c47d8
    type: playbook
    task:
      id: ecdbf6bf-4f85-4d1e-9752-f1ea454c47d8
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.

        NOTE: This playbook should be run only when the playbook's context is using the "Private to sub-playbook" option.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: device_filter_string,using
      AdditionalPollingCommandArgValues:
        simple: ${inputs.target},${inputs.PanoramaInstance}
      Ids:
        complex:
          root: PANOS.JobStatus
          accessor: id
          transformers:
          - operator: LastArrayElement
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: id
      PollingCommandName:
        simple: pan-os-platform-get-jobs
      Timeout:
        simple: "20"
      dt:
        simple: PANOS.JobStatus(val.status!=="FIN").id
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      scriptArguments:
        AdditionalPollingCommandArgNames:
          simple: device_filter_string,using
        AdditionalPollingCommandArgValues:
          simple: ${inputs.target},${incident.panosnetworkoperationspanoramainstance}
        Ids:
          complex:
            root: PANOS.JobStatus
            accessor: id
            transformers:
            - operator: LastArrayElement
        Interval:
          simple: "1"
        PollingCommandArgName:
          simple: id
        PollingCommandName:
          simple: pan-os-platform-get-jobs
        Timeout:
          simple: "20"
        dt:
          simple: PANOS.JobStatus(val.status!=="FIN").id
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 7c2615bc-5854-4451-ae30-ca8c7a9bd806
    type: condition
    task:
      id: 7c2615bc-5854-4451-ae30-ca8c7a9bd806
      version: -1
      name: Did it complete?
      description: Check if the software installation finished successfully.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: PANOS.JobStatus
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: PANOS.JobStatus.type
                      iscontext: true
                    right:
                      value:
                        simple: SWInstall
                accessor: status
            iscontext: true
          right:
            value:
              simple: FIN
      - - operator: isEqualString
          left:
            value:
              complex:
                root: PANOS.JobStatus
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: PANOS.JobStatus.type
                      iscontext: true
                    right:
                      value:
                        simple: SWInstall
                accessor: result
            iscontext: true
          right:
            value:
              simple: OK
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 970
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 8bdcd856-c97b-456d-8c3b-5cc22067d7e8
    type: regular
    task:
      id: 8bdcd856-c97b-456d-8c3b-5cc22067d7e8
      version: -1
      name: Get jobs again to check status
      description: Gets all the jobs from the devices in the environment, or a single
        job when the ID is specified.
      script: Panorama|||pan-os-platform-get-jobs
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      id:
        complex:
          root: PANOS.JobStatus
          accessor: id
          transformers:
          - operator: LastArrayElement
      using:
        simple: ${inputs.PanoramaInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 815
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 9d874d1c-81d5-426e-8ec8-664698e98862
    type: condition
    task:
      id: 9d874d1c-81d5-426e-8ec8-664698e98862
      version: -1
      name: Is the job active?
      description: It's possible that, if software has already been installed, then
        we don't get an active job for it.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      ACT:
      - "3"
      FIN:
      - "4"
    separatecontext: false
    conditions:
    - label: ACT
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.JobStatus.status
            iscontext: true
          right:
            value:
              simple: ACT
    - label: FIN
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.JobStatus.status
            iscontext: true
          right:
            value:
              simple: FIN
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: cd2775cb-663a-4c71-86c5-9c13739e7b9d
    type: title
    task:
      id: cd2775cb-663a-4c71-86c5-9c13739e7b9d
      version: -1
      name: Finish
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1160
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 1835daef-48ea-4a28-b6b1-35e5da9228f2
    type: regular
    task:
      id: 1835daef-48ea-4a28-b6b1-35e5da9228f2
      version: -1
      name: Fail message
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Software install job failed.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 990,
          "y": 1316
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 2a665130-167b-4c64-bb23-c76c732b0a90
    type: regular
    task:
      id: 2a665130-167b-4c64-bb23-c76c732b0a90
      version: -1
      name: Set Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      details:
        simple: Installing Software Version ${inputs.target_version}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 40
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: fb8a9838-77d3-423e-a419-791e553a91b1
    type: regular
    task:
      id: fb8a9838-77d3-423e-a419-791e553a91b1
      version: -1
      name: Set Description
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      details:
        simple: Software Install failed.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 990,
          "y": 1155
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 6045175d-2ddf-42f6-8908-12ba2db9be2b
    type: regular
    task:
      id: 6045175d-2ddf-42f6-8908-12ba2db9be2b
      version: -1
      name: Clear Context for Looping
      description: "Delete field from context.\n\nThis automation runs using the default
        Limited User role, unless you explicitly change the permissions.\nFor more
        information, see the section about permissions here:\n- For Cortex XSOAR 6
        see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      all:
        simple: "yes"
      subplaybook:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "6_3_ACT": 0.59
    },
    "paper": {
      "dimensions": {
        "height": 1616,
        "width": 920,
        "x": 450,
        "y": -230
      }
    }
  }
inputs:
- key: target_version
  value: {}
  required: false
  description: Target Version to INstall
  playbookInputQuery: null
- key: target
  value: {}
  required: false
  description: Target Device
  playbookInputQuery: null
- key: PanoramaInstance
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
inputSections:
- inputs:
  - target_version
  - target
  - PanoramaInstance
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs: []
  name: General (Outputs group)
  description: Generic group for outputs
outputs: []
dirtyInputs: true
