id: PAN-OS Network Operations - Get HA Pair Status
version: 6
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Get HA Pair Status
description: Determines which device in a HA pair is active or passive, and if the
  pair is an active-passive or active-active mode.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d5860d58-d9c8-40d3-80c5-f3646eb45697
    type: start
    task:
      id: d5860d58-d9c8-40d3-80c5-f3646eb45697
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -40
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: ce828d96-21a2-4dc5-99cf-35eb6c8afa8e
    type: regular
    task:
      id: ce828d96-21a2-4dc5-99cf-35eb6c8afa8e
      version: -1
      name: Get HA state
      description: Gets the HA state and associated details from the given device
        and any other details.
      script: Panorama|||pan-os-platform-get-ha-state
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      target:
        simple: ${inputs.target}
      using:
        simple: ${inputs.PanoramaInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: d4be9951-77ac-4e0c-a060-2fd5864cc82a
    type: condition
    task:
      id: d4be9951-77ac-4e0c-a060-2fd5864cc82a
      version: -1
      name: Is there a peer?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: PANOS.HAState.peer
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 7af345e9-d770-4ab6-b413-f26d06379c01
    type: regular
    task:
      id: 7af345e9-d770-4ab6-b413-f26d06379c01
      version: -1
      name: Get Peer HA State
      description: Gets the HA state and associated details from the given device
        and any other details.
      script: Panorama|||pan-os-platform-get-ha-state
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "5"
      - "6"
    scriptarguments:
      target:
        simple: ${PANOS.HAState.peer}
      using:
        simple: ${inputs.PanoramaInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 520
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 93aaa1be-a39b-46a2-80dc-7144a4bfe034
    type: title
    task:
      id: 93aaa1be-a39b-46a2-80dc-7144a4bfe034
      version: -1
      name: Finish - No HA
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1070,
          "y": 920
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 0288f615-debf-4cab-874e-001f7d09c7ff
    type: regular
    task:
      id: 0288f615-debf-4cab-874e-001f7d09c7ff
      version: -1
      name: Set Active Peer
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: ActiveDevice
      value:
        complex:
          root: PANOS.HAState
          filters:
          - - operator: isTrue
              left:
                value:
                  simple: PANOS.HAState.active
                iscontext: true
          accessor: hostid
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 250,
          "y": 700
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: c8c04c87-4664-4eff-9655-eab75a33b7b0
    type: regular
    task:
      id: c8c04c87-4664-4eff-9655-eab75a33b7b0
      version: -1
      name: Set Passive Peer
      description: |-
        Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: PassiveDevice
      value:
        complex:
          root: PANOS.HAState
          filters:
          - - operator: isFalse
              left:
                value:
                  simple: PANOS.HAState.active
                iscontext: true
          - - operator: isEqualString
              left:
                value:
                  simple: PANOS.HAState.status
                iscontext: true
              right:
                value:
                  simple: passive
          accessor: hostid
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 660,
          "y": 700
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: e3f637d9-683e-45b5-89fd-8229d59ae56a
    type: title
    task:
      id: e3f637d9-683e-45b5-89fd-8229d59ae56a
      version: -1
      name: Finish HA Discovery
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 10ba40cb-3a6b-482a-804b-320780bfac9a
    type: regular
    task:
      id: 10ba40cb-3a6b-482a-804b-320780bfac9a
      version: -1
      name: Clear Context for Looping
      description: "Delete field from context.\n\nThis automation runs using the default
        Limited User role, unless you explicitly change the permissions.\nFor more
        information, see the section about permissions here:\n- For Cortex XSOAR 6
        see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      subplaybook:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 70
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1020,
        "width": 1200,
        "x": 250,
        "y": -40
      }
    }
  }
inputs:
- key: target
  value: {}
  required: false
  description: Target firewall
  playbookInputQuery: null
- key: PanoramaInstance
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
inputSections:
- inputs:
  - target
  - PanoramaInstance
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs:
  - ActiveDevice
  - PassiveDevice
  name: General (Outputs group)
  description: Generic group for outputs
outputs:
- contextPath: ActiveDevice
  description: The active firewall
  type: string
- contextPath: PassiveDevice
  description: The passive firewall - may be empty.
  type: string
dirtyInputs: true
