id: PAN-OS Network Operations - Start Device Upgrades
version: 9
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Start Device Upgrades
description: |-
  This playbook is used by the Batch Upgrade playbook to start (either manually or automatically) groups of Device Upgrade alerts.

  It works by first retrieving the devices that have upgrades pending, then marking the pause tasks within them complete in batches.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: c40c8791-2ff3-4793-8768-2edc199f0059
    type: start
    task:
      id: c40c8791-2ff3-4793-8768-2edc199f0059
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -80
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 44406794-5660-4b7e-a32a-626a2f0e9a96
    type: condition
    task:
      id: 44406794-5660-4b7e-a32a-626a2f0e9a96
      version: -1
      name: Is auto-upgrade enabled?
      description: Check for automatic upgrade switch
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isTrue
          left:
            value:
              simple: inputs.Automatically Upgrade
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: e83a812e-8831-4628-bbd1-8502ef742621
    type: regular
    task:
      id: e83a812e-8831-4628-bbd1-8502ef742621
      version: -1
      name: Start device upgrades
      description: commands.local.cmd.task.complete
      script: Builtin|||taskComplete
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      alertId:
        simple: ${inputs.alert_ids}
      id:
        simple: start-upgrade
      incidentId:
        complex:
          root: inputs.incident_ids
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 46eb0257-4c19-44ab-a29e-e0ae34a11485
    type: condition
    task:
      id: 46eb0257-4c19-44ab-a29e-e0ae34a11485
      version: -1
      name: Begin Upgrades
      description: |-
        #### Do you want to start upgrading all devices?

        This will **start upgrades** on all of the devices, which may result in an **interruption to network traffic.**
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "No":
      - "4"
      "Yes":
      - "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 720,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to: null
      subject: null
      body:
        simple: |-
          Do you want to start all device upgrades?

          This will start upgrades on the following devices;

          ${inputs.PanoramaDevices}

          ${inputs.NGFWDevices}
      methods: []
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
      replyOptions:
      - "Yes"
      - "No"
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 53c1ac20-e57f-422e-9cc2-decc51c25010
    type: title
    task:
      id: 53c1ac20-e57f-422e-9cc2-decc51c25010
      version: -1
      name: DONE
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 758
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: b86f7cc3-eec3-47b6-8139-24b7b94ecda6
    type: regular
    task:
      id: b86f7cc3-eec3-47b6-8139-24b7b94ecda6
      version: -1
      name: Clear Context for Looping
      description: "Delete field from context.\n\nThis automation runs using the default
        Limited User role, unless you explicitly change the permissions.\nFor more
        information, see the section about permissions here:\n- For Cortex XSOAR 6
        see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      subplaybook:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 898,
        "width": 650,
        "x": 450,
        "y": -80
      }
    }
  }
inputs:
- key: Automatically Upgrade
  value:
    simple: ${alert.panosnetworkoperationsautomaticupgrade}
  required: false
  description: If set to true, will automatically start all device ugprades.
  playbookInputQuery: null
- key: alert_ids
  value: {}
  required: false
  description: List of alert IDs corresponding to device upgrade alerts to start.
  playbookInputQuery: null
- key: PanoramaDevices
  value: {}
  required: false
  description: A list of Panorama device IDs to upgrade
  playbookInputQuery: null
- key: NGFWDevices
  value: {}
  required: false
  description: A list of NGFW device IDs to upgrade
  playbookInputQuery: null
inputSections:
- inputs:
  - Automatically Upgrade
  - alert_ids
  - PanoramaDevices
  - NGFWDevices
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs: []
  name: General (Outputs group)
  description: Generic group for outputs
outputs: []
dirtyInputs: true
