id: PAN-OS Network Operations - Download Software
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Download Software
description: Download PAN-OS System software.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 0b119e62-30d5-4598-8a8f-9ab6b2689b8a
    type: start
    task:
      id: 0b119e62-30d5-4598-8a8f-9ab6b2689b8a
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -510
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 6825c741-b2f2-42a0-8a65-ccecc0a0eb79
    type: regular
    task:
      id: 6825c741-b2f2-42a0-8a65-ccecc0a0eb79
      version: -1
      name: Download the Software Version
      description: Download The provided software version onto the device.
      script: '|||pan-os-platform-download-software'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      retry-count:
        simple: "5"
      retry-interval:
        simple: "60"
      version:
        simple: ${inputs.target_version}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -225
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: d7a8d48b-f0c5-4698-8c03-918ef1dc3f5a
    type: regular
    task:
      id: d7a8d48b-f0c5-4698-8c03-918ef1dc3f5a
      version: -1
      name: Get Jobs
      description: Get all the jobs from the devices in the environment.
      script: '|||pan-os-platform-get-jobs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      device_filter_string:
        simple: ${PANOS.DownloadStatus.Summary.hostid}
      ignore-outputs:
        simple: "false"
      job_type:
        simple: Downld
      status:
        simple: ACT
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: b2048d43-1322-43a1-8990-9421142a23fc
    type: playbook
    task:
      id: b2048d43-1322-43a1-8990-9421142a23fc
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: device_filter_string
      AdditionalPollingCommandArgValues:
        simple: ${inputs.target}
      Ids:
        complex:
          root: PANOS.JobStatus
          accessor: id
          transformers:
          - operator: LastArrayElement
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: id
      PollingCommandName:
        simple: pan-os-platform-get-jobs
      Timeout:
        simple: ${inputs.timeout}
      dt:
        simple: PANOS.JobStatus(val.status!=="FIN").id
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      scriptArguments:
        Ids:
          complex:
            root: PANOS.JobStatus
            accessor: id
            transformers:
            - operator: LastArrayElement
        Interval:
          simple: "1"
        PollingCommandArgName:
          simple: id
        PollingCommandName:
          simple: pan-os-platform-get-jobs
        Timeout:
          simple: "30"
        dt:
          simple: PANOS.JobStatus(val.status!=="FIN").id
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 440,
          "y": 670
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 56713fb4-e811-4266-8477-e84e080c437f
    type: regular
    task:
      id: 56713fb4-e811-4266-8477-e84e080c437f
      version: -1
      name: Get jobs again to check status
      description: Get all the jobs from the devices in the environment, or a single
        job when ID is specified.
      script: '|||pan-os-platform-get-jobs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      id:
        complex:
          root: PANOS.JobStatus
          accessor: id
          transformers:
          - operator: LastArrayElement
      target:
        simple: ${inputs.target}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: b91f3691-5ccf-4e2c-831f-7d87220b178f
    type: condition
    task:
      id: b91f3691-5ccf-4e2c-831f-7d87220b178f
      version: -1
      name: Did it complete?
      description: True if the software download was successful
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.JobStatus.status
            iscontext: true
          right:
            value:
              simple: FIN
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.JobStatus.result
            iscontext: true
          right:
            value:
              simple: OK
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 325aedfc-ca4e-4cda-81dc-05f6a4ecba5c
    type: title
    task:
      id: 325aedfc-ca4e-4cda-81dc-05f6a4ecba5c
      version: -1
      name: Finish
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 4f600917-fecd-45fd-8f43-65b87f4b5f96
    type: regular
    task:
      id: 4f600917-fecd-45fd-8f43-65b87f4b5f96
      version: -1
      name: Fail message
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Download job failed.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 870,
          "y": 1165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: e47caf2f-0663-4749-8d6b-f0c6be985745
    type: regular
    task:
      id: e47caf2f-0663-4749-8d6b-f0c6be985745
      version: -1
      name: Set Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      description:
        simple: Downloading Software Version ${inputs.target_version}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 858e2777-f396-4e72-8ad3-8bc74b4c2ebb
    type: regular
    task:
      id: 858e2777-f396-4e72-8ad3-8bc74b4c2ebb
      version: -1
      name: Wait for job to get processed
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      seconds:
        simple: "30"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 0757d95c-bf16-4ef5-857f-48dc497b2dd6
    type: condition
    task:
      id: 0757d95c-bf16-4ef5-857f-48dc497b2dd6
      version: -1
      name: Did we get a job?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: PANOS.JobStatus.id
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 5c1b2096-3647-4186-8ec9-e67b68fc69e1
    type: regular
    task:
      id: 5c1b2096-3647-4186-8ec9-e67b68fc69e1
      version: -1
      name: Get Jobs
      description: Get all the jobs from the devices in the environment.
      script: '|||pan-os-platform-get-jobs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      device_filter_string:
        simple: ${PANOS.DownloadStatus.Summary.hostid}
      ignore-outputs:
        simple: "false"
      job_type:
        simple: Downld
      status:
        simple: ACT
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1770,
        "width": 850,
        "x": 440,
        "y": -510
      }
    }
  }
inputs:
- key: target
  value: {}
  required: false
  description: Target Firewall - Serial or IP address
  playbookInputQuery: null
- key: target_version
  value: {}
  required: false
  description: Target Software Version to Download
  playbookInputQuery: null
- key: timeout
  value:
    simple: "45"
  required: false
  description: Default max timeout value
  playbookInputQuery: null
outputs: []
