id: PAN-OS Network Operations - Install Software
version: 5
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Install Software
description: Installs PAN-OS system software.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1114c20f-b7a4-4d52-8313-7c30d02cd7c8
    type: start
    task:
      id: 1114c20f-b7a4-4d52-8313-7c30d02cd7c8
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -80
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 25154c7f-0d20-4a04-842d-40caff7446ad
    type: regular
    task:
      id: 25154c7f-0d20-4a04-842d-40caff7446ad
      version: -1
      name: Install the given software version
      description: Install the given software version onto the device. Download the
        software first with
      script: '|||pan-os-platform-install-software'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      version:
        simple: ${inputs.target_version}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: a7bca76c-0a39-439e-895d-96f19928534a
    type: regular
    task:
      id: a7bca76c-0a39-439e-895d-96f19928534a
      version: -1
      name: Get Jobs
      description: Get all the jobs from the devices in the environment.
      script: '|||pan-os-platform-get-jobs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      job_type:
        simple: SWInstall
      status:
        simple: ACT
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 511c4b5c-dfd9-434f-884a-776bb89a810b
    type: playbook
    task:
      id: 511c4b5c-dfd9-434f-884a-776bb89a810b
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: device_filter_string
      AdditionalPollingCommandArgValues:
        simple: ${inputs.target}
      Ids:
        complex:
          root: PANOS.JobStatus
          accessor: id
          transformers:
          - operator: LastArrayElement
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: id
      PollingCommandName:
        simple: pan-os-platform-get-jobs
      Timeout:
        simple: "20"
      dt:
        simple: PANOS.JobStatus(val.status!=="FIN").id
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      scriptArguments:
        Ids:
          complex:
            root: PANOS.JobStatus
            accessor: id
            transformers:
            - operator: LastArrayElement
        Interval:
          simple: "1"
        PollingCommandArgName:
          simple: id
        PollingCommandName:
          simple: pan-os-platform-get-jobs
        Timeout:
          simple: "20"
        dt:
          simple: PANOS.JobStatus(val.status!=="FIN").id
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 450,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 426f96a1-80ed-463f-8a3e-384ec12db7f7
    type: condition
    task:
      id: 426f96a1-80ed-463f-8a3e-384ec12db7f7
      version: -1
      name: Did it complete?
      description: Check if the software installation finished successfully.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: PANOS.JobStatus
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: PANOS.JobStatus.type
                      iscontext: true
                    right:
                      value:
                        simple: SWInstall
                accessor: status
            iscontext: true
          right:
            value:
              simple: FIN
      - - operator: isEqualString
          left:
            value:
              complex:
                root: PANOS.JobStatus
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: PANOS.JobStatus.type
                      iscontext: true
                    right:
                      value:
                        simple: SWInstall
                accessor: result
            iscontext: true
          right:
            value:
              simple: OK
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 970
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 1bc37e9e-0b88-4cad-85c8-38fe7910192c
    type: regular
    task:
      id: 1bc37e9e-0b88-4cad-85c8-38fe7910192c
      version: -1
      name: Get jobs again to check status
      description: Get all the jobs from the devices in the environment, or a single
        job when ID is specified.
      script: '|||pan-os-platform-get-jobs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      id:
        complex:
          root: PANOS.JobStatus
          accessor: id
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 815
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 8e9ac62e-e4da-4503-80ab-df3e0517c733
    type: condition
    task:
      id: 8e9ac62e-e4da-4503-80ab-df3e0517c733
      version: -1
      name: Is the job active?
      description: It's possible that, if software has already been installed, then
        we don't get an active job for it.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      ACT:
      - "3"
      FIN:
      - "4"
    separatecontext: false
    conditions:
    - label: ACT
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.JobStatus.status
            iscontext: true
          right:
            value:
              simple: ACT
    - label: FIN
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.JobStatus.status
            iscontext: true
          right:
            value:
              simple: FIN
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: fcf2d694-d215-4789-818c-247709722a63
    type: title
    task:
      id: fcf2d694-d215-4789-818c-247709722a63
      version: -1
      name: Finish
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1160
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: abb1275a-2d99-4c32-8319-5233aa2d542e
    type: regular
    task:
      id: abb1275a-2d99-4c32-8319-5233aa2d542e
      version: -1
      name: Fail message
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Software install job failed.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 890,
          "y": 1335
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 2fedbf9e-9f6f-4bab-825f-8311a243278e
    type: regular
    task:
      id: 2fedbf9e-9f6f-4bab-825f-8311a243278e
      version: -1
      name: Set Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      description:
        simple: Installing Software Version ${inputs.target_version}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 40
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 82d4caa2-d0e3-46ab-813a-d7d38f5b461b
    type: regular
    task:
      id: 82d4caa2-d0e3-46ab-813a-d7d38f5b461b
      version: -1
      name: Set Description
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      description:
        simple: Software Install failed.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 890,
          "y": 1160
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1510,
        "width": 820,
        "x": 450,
        "y": -80
      }
    }
  }
inputs:
- key: target_version
  value: {}
  required: false
  description: Target Version to INstall
  playbookInputQuery: null
- key: target
  value: {}
  required: false
  description: Target Device
  playbookInputQuery: null
outputs: []
