id: PAN-OS Network Operations - Download Software
version: 6
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Download Software
description: Download PAN-OS System software.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 7ed246ff-11db-47b7-8c8d-cf2dcdee8ebb
    type: start
    task:
      id: 7ed246ff-11db-47b7-8c8d-cf2dcdee8ebb
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 678d30ea-74c7-40a8-bd58-d30fd817bd59
    type: regular
    task:
      id: 678d30ea-74c7-40a8-bd58-d30fd817bd59
      version: -1
      name: Download the Software Version
      description: Downloads the provided software version onto the device.
      script: Panorama|||pan-os-platform-download-software
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      retry-count:
        simple: "5"
      retry-interval:
        simple: "60"
      using:
        simple: ${inputs.PanoramaInstance}
      version:
        simple: ${inputs.target_version}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -225
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: d32e7eea-0cac-4210-ae15-233e6f045de3
    type: regular
    task:
      id: d32e7eea-0cac-4210-ae15-233e6f045de3
      version: -1
      name: Get Jobs
      description: Gets all the jobs from the devices in the environment, or a single
        job when the ID is specified.
      script: Panorama|||pan-os-platform-get-jobs
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      device_filter_string:
        simple: ${PANOS.DownloadStatus.Summary.hostid}
      ignore-outputs:
        simple: "false"
      job_type:
        simple: Downld
      status:
        simple: ACT
      using:
        simple: ${inputs.PanoramaInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: f974b36a-539b-4e5b-b51d-1c8493ea7565
    type: playbook
    task:
      id: f974b36a-539b-4e5b-b51d-1c8493ea7565
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.

        NOTE: This playbook should be run only when the playbook's context is using the "Private to sub-playbook" option.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: device_filter_string,using
      AdditionalPollingCommandArgValues:
        simple: ${inputs.target},${inputs.PanoramaInstance}
      Ids:
        complex:
          root: PANOS.JobStatus
          accessor: id
          transformers:
          - operator: LastArrayElement
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: id
      PollingCommandName:
        simple: pan-os-platform-get-jobs
      Timeout:
        simple: ${inputs.timeout}
      dt:
        simple: PANOS.JobStatus(val.status!=="FIN").id
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      scriptArguments:
        AdditionalPollingCommandArgNames:
          simple: device_filter_string,using
        AdditionalPollingCommandArgValues:
          simple: ${inputs.target},${incident.panosnetworkoperationspanoramainstance}
        Ids:
          complex:
            root: PANOS.JobStatus
            accessor: id
            transformers:
            - operator: LastArrayElement
        Interval:
          simple: "1"
        PollingCommandArgName:
          simple: id
        PollingCommandName:
          simple: pan-os-platform-get-jobs
        Timeout:
          simple: ${inputs.timeout}
        dt:
          simple: PANOS.JobStatus(val.status!=="FIN").id
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 440,
          "y": 670
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: f46ea162-9214-48e1-a254-2c90dab7656e
    type: regular
    task:
      id: f46ea162-9214-48e1-a254-2c90dab7656e
      version: -1
      name: Get jobs again to check status
      description: Gets all the jobs from the devices in the environment, or a single
        job when the ID is specified.
      script: Panorama|||pan-os-platform-get-jobs
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      id:
        complex:
          root: PANOS.JobStatus
          accessor: id
          transformers:
          - operator: LastArrayElement
      target:
        simple: ${inputs.target}
      using:
        simple: ${inputs.PanoramaInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 6e51eaa7-f883-44a3-a22a-7137593a69fb
    type: condition
    task:
      id: 6e51eaa7-f883-44a3-a22a-7137593a69fb
      version: -1
      name: Did it complete?
      description: True if the software download was successful
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.JobStatus.status
            iscontext: true
          right:
            value:
              simple: FIN
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.JobStatus.result
            iscontext: true
          right:
            value:
              simple: OK
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 90b71bd2-0492-429c-8add-8b406bdcc1d5
    type: title
    task:
      id: 90b71bd2-0492-429c-8add-8b406bdcc1d5
      version: -1
      name: Finish
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: bedef0f5-6baf-4984-92f9-8d8c24a37bcf
    type: regular
    task:
      id: bedef0f5-6baf-4984-92f9-8d8c24a37bcf
      version: -1
      name: Fail message
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Download job failed.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 870,
          "y": 1165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 76081e3d-8b50-47fd-a026-4232bf124a21
    type: regular
    task:
      id: 76081e3d-8b50-47fd-a026-4232bf124a21
      version: -1
      name: Set Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      details:
        simple: Downloading Software Version ${inputs.target_version}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: c8c773b8-a88a-4469-96aa-8bc5642f639c
    type: regular
    task:
      id: c8c773b8-a88a-4469-96aa-8bc5642f639c
      version: -1
      name: Wait for job to get processed
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      seconds:
        simple: "30"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 8b5c88d9-38f3-4c98-8dfb-4b920181fbd6
    type: condition
    task:
      id: 8b5c88d9-38f3-4c98-8dfb-4b920181fbd6
      version: -1
      name: Did we get a job?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: PANOS.JobStatus.id
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 15d1474c-4d94-4b21-8ec6-56ccf30ea8a2
    type: regular
    task:
      id: 15d1474c-4d94-4b21-8ec6-56ccf30ea8a2
      version: -1
      name: Get Jobs
      description: Gets all the jobs from the devices in the environment, or a single
        job when the ID is specified.
      script: Panorama|||pan-os-platform-get-jobs
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      device_filter_string:
        simple: ${PANOS.DownloadStatus.Summary.hostid}
      ignore-outputs:
        simple: "false"
      job_type:
        simple: Downld
      status:
        simple: ACT
      using:
        simple: ${inputs.PanoramaInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 4d32200a-3f94-47f4-a46e-03ea42f700c3
    type: regular
    task:
      id: 4d32200a-3f94-47f4-a46e-03ea42f700c3
      version: -1
      name: Clear Context for Looping
      description: "Delete field from context.\n\nThis automation runs using the default
        Limited User role, unless you explicitly change the permissions.\nFor more
        information, see the section about permissions here:\n- For Cortex XSOAR 6
        see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      all:
        simple: "yes"
      subplaybook:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -540
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1890,
        "width": 850,
        "x": 440,
        "y": -650
      }
    }
  }
inputs:
- key: target
  value: {}
  required: false
  description: Target Firewall - Serial or IP address
  playbookInputQuery: null
- key: target_version
  value: {}
  required: false
  description: Target Software Version to Download
  playbookInputQuery: null
- key: timeout
  value:
    simple: "45"
  required: false
  description: Default max timeout value
  playbookInputQuery: null
- key: PanoramaInstance
  value: {}
  required: true
  description: ""
  playbookInputQuery: null
inputSections:
- inputs:
  - target
  - target_version
  - timeout
  - PanoramaInstance
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs: []
  name: General (Outputs group)
  description: Generic group for outputs
outputs: []
dirtyInputs: true
