id: f36e3d36-e5d7-480c-80ce-2db848e1eebd
version: 27
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Upgrade Assurance
description: Runs a series of tests based on the upgrade assurance commands and prompts
  if any fail - also generates reports and other information that is useful in the
  assurance process.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b8463b92-38b1-46ae-821e-e6c895b59a1b
    type: start
    task:
      id: b8463b92-38b1-46ae-821e-e6c895b59a1b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 3789ab9c-f5d1-49e3-884f-a1a67a495cc2
    type: regular
    task:
      id: 3789ab9c-f5d1-49e3-884f-a1a67a495cc2
      version: -1
      name: Aborted process.
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      description:
        simple: Assurance testing aborted.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: b862ab81-e717-466d-8d23-033ca4ad32c7
    type: collection
    task:
      id: b862ab81-e717-466d-8d23-033ca4ad32c7
      version: -1
      name: Second Snapshot Trigger
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: ${incident.owner}
      subject:
        simple: Waiting for trigger for Snapshot on ${incident.panosnetworkoperationsupgradetargetfirewall}
      body:
        simple: 'The assurance process is paused, waiting for manual confirmation
          to take the second snapshot and run the comparsion on firewall ${incident.panosnetworkoperationsupgradetargetfirewall}. '
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: |-
            ### Do you want to continue?
            *Choosing Yes will run the second snapshot, and proceed with the comparsion*
        required: true
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      title: Second Snapshot Confirmation
      description: Mark complete when you're ready to take the second snapshot and
        run the comparsion between the two.
      sender: Your SOC team
      expired: false
      totalanswers: 0
    formDisplay:
      headerbackgroundcolor: '#ff0000'
      headerfontcolor: ""
      sender: ""
      bodybackgroundcolor: ""
      bodyfontcolor: ""
      submitbuttonbackgroundcolor: '#f50057'
      submitbuttonfontcolor: ""
      submittext: ""
      isexternalrtl: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: e34dd71d-28ff-4067-89a0-dbef5dbad4bf
    type: condition
    task:
      id: e34dd71d-28ff-4067-89a0-dbef5dbad4bf
      version: -1
      name: Continue?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Second Snapshot Confirmation.Answers.0
            iscontext: true
          right:
            value:
              simple: "Yes"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 520
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 280cd7cd-a56d-424f-8aad-dbf2b88c7476
    type: playbook
    task:
      id: 280cd7cd-a56d-424f-8aad-dbf2b88c7476
      version: -1
      name: PAN-OS Network Operations - Upgrade Assurance - First Snapshot
      playbookName: PAN-OS Network Operations - Upgrade Assurance - First Snapshot
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 5bd44314-3cc0-4a9c-8da5-a237fde0d080
    type: playbook
    task:
      id: 5bd44314-3cc0-4a9c-8da5-a237fde0d080
      version: -1
      name: PAN-OS Network Operations - Upgrade Assurance - Assurance Test
      playbookName: PAN-OS Network Operations - Upgrade Assurance - Assurance Test
      type: playbook
      iscommand: false
      brand: ""
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 925,
        "width": 790,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: target
  value:
    simple: ${incident.panosnetworkoperationstarget}
  required: true
  description: Target firewall - helpful if running this playbook in a loop.
  playbookInputQuery: null
outputs: []
