id: 91798901-7d40-4e34-8ecf-1f0119c30b6d
version: 4
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Check if Device Onboarded
description: Checks for the given serial number to validate if it's connected to Panorama.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5b25245c-9306-44ca-8f6e-2293820c8348
    type: start
    task:
      id: 5b25245c-9306-44ca-8f6e-2293820c8348
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 26f06e9a-4d2b-48fe-83c5-a8ff1d31cbba
    type: regular
    task:
      id: 26f06e9a-4d2b-48fe-83c5-a8ff1d31cbba
      version: -1
      name: Get Device By Serial
      description: Returns indicator custom fields into the context by the given query.
      scriptName: GetIndicatorFieldsByQuery
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      query:
        simple: value:${inputs.serial}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 61fdc324-e754-430f-8ecf-ca15456b2b8c
    type: condition
    task:
      id: 61fdc324-e754-430f-8ecf-ca15456b2b8c
      version: -1
      name: Did we get a firewall?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: GetIndicatorFieldsByQuery
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 9e62a45d-558d-44fc-84c2-232bbe782c58
    type: regular
    task:
      id: 9e62a45d-558d-44fc-84c2-232bbe782c58
      version: -1
      name: Onboarding Process Complete
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 950
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 71092c1c-8265-4a1e-8558-c64c1f42b0bd
    type: regular
    task:
      id: 71092c1c-8265-4a1e-8558-c64c1f42b0bd
      version: -1
      name: Device not yet connected - reset the timer
      description: commands.local.cmd.reset.timer
      script: Builtin|||resetTimer
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      timerField:
        simple: pauseforpanorama
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 850,
          "y": 580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 58ed74bc-3fcc-492a-8e01-3022bba82853
    type: regular
    task:
      id: 58ed74bc-3fcc-492a-8e01-3022bba82853
      version: -1
      name: Associate the device indicator with this onboarding incident.
      description: commands.local.cmd.associate.indicators
      script: Builtin|||associateIndicatorsToIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      incidentId:
        simple: ${incident.id}
      indicatorsValues:
        simple: ${inputs.serial}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: bd0216d2-13aa-461a-899e-e2ec648b2c95
    type: title
    task:
      id: bd0216d2-13aa-461a-899e-e2ec648b2c95
      version: -1
      name: Start the Timer
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 850,
          "y": 785
        }
      }
    note: false
    timertriggers:
    - fieldname: pauseforpanorama
      action: start
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 8668ad3d-46a8-44c6-87b4-a2b216a0a009
    type: regular
    task:
      id: 8668ad3d-46a8-44c6-87b4-a2b216a0a009
      version: -1
      name: Update Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      onboardingstatus:
        simple: Firewall Onboarded
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 995,
        "width": 780,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: serial
  value:
    simple: ${incident.serialnumber}
  required: true
  description: Serial number of FW to check.
  playbookInputQuery:
outputs: []
