id: PAN-OS Network Operations - Incident Callback
version: 5
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Incident Callback
description: Checks to see if this incident has a parent incident and if so, links
  the two incidents.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: de5eacbb-9481-4507-8258-3acff97cabe5
    type: start
    task:
      id: de5eacbb-9481-4507-8258-3acff97cabe5
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 20
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 230cc56a-1b12-4dcc-8373-b21b3a02cf56
    type: regular
    task:
      id: 230cc56a-1b12-4dcc-8373-b21b3a02cf56
      version: -1
      name: Mark Complete
      description: commands.local.cmd.task.complete
      script: Builtin|||taskComplete
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      id:
        simple: ${incident.panosnetworkoperationsclosetaskid}
      incidentId:
        simple: ${incident.panosnetworkoperationsparentincidentid}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: dc183a2b-a042-4d8b-8064-c20b35293609
    type: title
    task:
      id: dc183a2b-a042-4d8b-8064-c20b35293609
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 19f083a6-1a32-4f23-8efc-ad4989cbcb9f
    type: condition
    task:
      id: 19f083a6-1a32-4f23-8efc-ad4989cbcb9f
      version: -1
      name: Do we have a parent task to mark complete?
      description: Chefcks if the incident callback needs to run.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: incident.panosnetworkoperationsclosetaskid
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 150
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 535,
        "width": 380,
        "x": 450,
        "y": 20
      }
    }
  }
inputs: []
outputs: []
