id: PAN-OS Network Operations - Check For Open CVEs
version: 4
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Check For Open CVEs
description: This playbook uses the Palo Alto Networks Security Advisories integration,
  if available, to compare all the running software versions in the environment with
  the list of Open CVEs and either automatically begins the upgrade process or initiates
  a case management process to do so.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 323ce83e-6f08-4774-8a6b-68b1d1e860df
    type: start
    task:
      id: 323ce83e-6f08-4774-8a6b-68b1d1e860df
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 979d8ae0-1ac2-459d-850b-ad5e910aba19
    type: condition
    task:
      id: 979d8ae0-1ac2-459d-850b-ad5e910aba19
      version: -1
      name: Is the Advisories integration enabled?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Palo_Alto_Networks_Security_Advisories
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 71914914-d6d3-4b17-8752-a4b4fe1f2013
    type: playbook
    task:
      id: 71914914-d6d3-4b17-8752-a4b4fe1f2013
      version: -1
      name: PAN-OS Network Operations - Check Version for CVEs
      description: Checks a specific version of software for any open CVEs, and if
        they exist, starts a domain upgrade for that system to a fixed version.
      playbookName: PAN-OS Network Operations - Check Version for CVEs
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      auto_upgrade:
        simple: "false"
      panos_version:
        complex:
          root: PANOS.ShowSystemInfo.Summary
          accessor: sw_version
          transformers:
          - operator: uniq
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 70ec6bba-eacd-4de5-82f1-31815131c7ea
    type: title
    task:
      id: 70ec6bba-eacd-4de5-82f1-31815131c7ea
      version: -1
      name: Finish
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 6485c0b2-ab72-43c8-8c0d-d0a56ec026de
    type: regular
    task:
      id: 6485c0b2-ab72-43c8-8c0d-d0a56ec026de
      version: -1
      name: Get System Info
      description: Gets information from all PAN-OS systems in the topology.
      script: '|||pan-os-platform-get-system-info'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "2_4_#default#": 0.55
    },
    "paper": {
      "dimensions": {
        "height": 755,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
