id: 7409a83d-eab4-4acd-8b93-a4abc6a038e4
version: 5
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Get HA Pair Status
description: Determines which device in a HA pair is active or passive, and if the
  pair is an active-passive or active-active mode.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 30f9e301-5fb1-475f-88d0-faf1fd118b70
    type: start
    task:
      id: 30f9e301-5fb1-475f-88d0-faf1fd118b70
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: e1fb5109-93a1-4824-8ce8-1c7606a57b1f
    type: regular
    task:
      id: e1fb5109-93a1-4824-8ce8-1c7606a57b1f
      version: -1
      name: Get HA state
      description: Gets the HA state and associated details from the given device
        and any other details.
      script: '|||pan-os-platform-get-ha-state'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      target:
        simple: ${inputs.target}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: c2216111-7989-4997-8f67-9088fa0a5ca4
    type: condition
    task:
      id: c2216111-7989-4997-8f67-9088fa0a5ca4
      version: -1
      name: Is there a peer?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: PANOS.HAState.peer
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 794c5042-f3dc-4974-8001-af1d0037ad31
    type: regular
    task:
      id: 794c5042-f3dc-4974-8001-af1d0037ad31
      version: -1
      name: Get Peer HA State
      description: Gets the HA state and associated details from the given device
        and any other details.
      script: '|||pan-os-platform-get-ha-state'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
      - "6"
    scriptarguments:
      target:
        simple: ${PANOS.HAState.peer}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 520
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 846e695c-be25-45ae-83ca-b9ad489918e0
    type: title
    task:
      id: 846e695c-be25-45ae-83ca-b9ad489918e0
      version: -1
      name: Finish - No HA
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1070,
          "y": 920
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 4a29f2ac-3ca4-48ab-89b9-eb92d3a747a4
    type: regular
    task:
      id: 4a29f2ac-3ca4-48ab-89b9-eb92d3a747a4
      version: -1
      name: Set Active Peer
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: ActiveDevice
      value:
        complex:
          root: PANOS.HAState
          filters:
          - - operator: isTrue
              left:
                value:
                  simple: PANOS.HAState.active
                iscontext: true
          accessor: hostid
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 250,
          "y": 700
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: c8f7108a-c337-4900-8a50-b1b92412d1fa
    type: regular
    task:
      id: c8f7108a-c337-4900-8a50-b1b92412d1fa
      version: -1
      name: Set Passive Peer
      description: |-
        Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: PassiveDevice
      value:
        complex:
          root: PANOS.HAState
          filters:
          - - operator: isFalse
              left:
                value:
                  simple: PANOS.HAState.active
                iscontext: true
          - - operator: isEqualString
              left:
                value:
                  simple: PANOS.HAState.status
                iscontext: true
              right:
                value:
                  simple: passive
          accessor: hostid
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 660,
          "y": 700
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 1d40842a-4e32-4e68-855f-3b19e1af491f
    type: title
    task:
      id: 1d40842a-4e32-4e68-855f-3b19e1af491f
      version: -1
      name: Finish HA Discovery
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 935,
        "width": 1200,
        "x": 250,
        "y": 50
      }
    }
  }
inputs:
- key: target
  value: {}
  required: false
  description: Target firewall
  playbookInputQuery: null
outputs:
- contextPath: ActiveDevice
  description: The active firewall
  type: string
- contextPath: PassiveDevice
  description: The passive firewall - may be empty.
  type: string
