id: f36e3d36-e5d7-480c-80ce-2db848e1eebd
version: 14
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Upgrade Assurance
description: Runs a series of tests based on the upgrade assurance commands and prompts
  if any fail - also generates reports and other information that is useful in the
  assurance process.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3e1e7eb1-934f-4be8-8807-6aa5034a0995
    type: start
    task:
      id: 3e1e7eb1-934f-4be8-8807-6aa5034a0995
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 3cc46995-b05e-4537-833a-75dafb9e877e
    type: regular
    task:
      id: 3cc46995-b05e-4537-833a-75dafb9e877e
      version: -1
      name: Run Readiness Tests
      description: Runs checks to confirm a PAN-OS firewall is ready to be upgraded.
      script: '|||pan-os-assurance-run-readiness-checks'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      candidate_version:
        simple: ${incident.panosnetworkoperationsupgradetargetfirewallversion}
      check_list:
        simple: ${incident.readinesschecklist}
      firewall_serial:
        simple: ${inputs.target}
      min_content_version:
        simple: ${incident.minimumcontentversion}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: Readiness Check Result
      output:
        complex:
          root: FirewallAssurance
          accessor: ReadinessCheckResults
          transformers:
          - operator: ConvertKeysToTableFieldFormat
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 83b3c3e5-e627-4ac3-8d50-155d57a0c2e6
    type: condition
    task:
      id: 83b3c3e5-e627-4ac3-8d50-155d57a0c2e6
      version: -1
      name: Did we get failed tests?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: incident.readinesscheckresult.state
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: incident.readinesscheckresult.state
                      iscontext: true
                    right:
                      value:
                        simple: "false"
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 5cabef64-baa7-43ff-8c58-f91b78edcf5c
    type: collection
    task:
      id: 5cabef64-baa7-43ff-8c58-f91b78edcf5c
      version: -1
      name: Failed Readiness Test Confirmation
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 540
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: ${incident.owner}
      subject:
        simple: Upgrade Readiness Checks failed on ${incident.panosnetworkoperationsupgradetargetfirewall}
      body:
        simple: "The assurance process failed on the device ${incident.panosnetworkoperationsupgradetargetfirewall}.\n\nPlease
          validate the test result and choose whether to proceed or abort the assurance
          process. "
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: |-
            ### Do you want to continue?
            *Choosing Yes will continue with the upgrade assurance process, and if no other issues are present, the upgrade process itself.*
        required: true
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      title: Failed Readiness Test Confirmation
      description: The assurance process identified issues that might prevent the
        software upgrade from starting. Please confirm whether to proceed or abort
        the assurance process.
      sender: Your SOC team
      expired: false
      totalanswers: 0
    formDisplay:
      headerbackgroundcolor: '#ff0000'
      headerfontcolor: ""
      sender: ""
      bodybackgroundcolor: ""
      bodyfontcolor: ""
      submitbuttonbackgroundcolor: '#f50057'
      submitbuttonfontcolor: ""
      submittext: ""
      isexternalrtl: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 1fe712da-a69d-4fc3-8c1a-6fe839b22bd5
    type: condition
    task:
      id: 1fe712da-a69d-4fc3-8c1a-6fe839b22bd5
      version: -1
      name: Continue?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Failed Readiness Test Confirmation.Answers.0
            iscontext: true
          right:
            value:
              simple: "Yes"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 984a0fb4-cc9f-412c-80fb-2243c30227ef
    type: regular
    task:
      id: 984a0fb4-cc9f-412c-80fb-2243c30227ef
      version: -1
      name: Take the first device snapshot
      description: Takes a snapshot of the operational state of the system.
      script: '|||pan-os-assurance-run-snapshot'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
      - "7"
    scriptarguments:
      firewall_serial:
        simple: ${incident.panosnetworkoperationsupgradetargetfirewall}
      snapshot_name:
        simple: first_snapshot
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 900
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: bae35a92-c49f-4e27-8860-740201a1e988
    type: regular
    task:
      id: bae35a92-c49f-4e27-8860-740201a1e988
      version: -1
      name: Aborted process.
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      description:
        simple: Assurance testing aborted.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 1500
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 359c4aaf-eb1d-4960-8ccc-d82886c41c2e
    type: collection
    task:
      id: 359c4aaf-eb1d-4960-8ccc-d82886c41c2e
      version: -1
      name: Second Snapshot Trigger
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: ${incident.owner}
      subject:
        simple: Waiting for trigger for Snapshot on ${incident.panosnetworkoperationsupgradetargetfirewall}
      body:
        simple: 'The assurance process is paused, waiting for manual confirmation
          to take the second snapshot and run the comparsion on firewall ${incident.panosnetworkoperationsupgradetargetfirewall}. '
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: |-
            ### Do you want to continue?
            *Choosing Yes will run the second snapshot, and proceed with the comparsion*
        required: true
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      title: Second Snapshot Confirmation
      description: Mark complete when you're ready to take the second snapshot and
        run the comparsion between the two.
      sender: Your SOC team
      expired: false
      totalanswers: 0
    formDisplay:
      headerbackgroundcolor: '#ff0000'
      headerfontcolor: ""
      sender: ""
      bodybackgroundcolor: ""
      bodyfontcolor: ""
      submitbuttonbackgroundcolor: '#f50057'
      submitbuttonfontcolor: ""
      submittext: ""
      isexternalrtl: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 2202f2bf-4e9d-490e-88ff-7def6846bf5e
    type: condition
    task:
      id: 2202f2bf-4e9d-490e-88ff-7def6846bf5e
      version: -1
      name: Continue?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Failed Readiness Test Confirmation.Answers.0
            iscontext: true
          right:
            value:
              simple: "Yes"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 0723bf9a-9e0b-41c4-857e-469896615d15
    type: regular
    task:
      id: 0723bf9a-9e0b-41c4-857e-469896615d15
      version: -1
      name: Take the Second snapshot
      description: Takes a snapshot of the operational state of the system.
      script: '|||pan-os-assurance-run-snapshot'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
      - "12"
    scriptarguments:
      firewall_serial:
        simple: ${incident.panosnetworkoperationsupgradetargetfirewall}
      snapshot_name:
        simple: second_snapshot
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1500
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 96108d1a-bf4f-4f95-8874-0b03dc948afe
    type: regular
    task:
      id: 96108d1a-bf4f-4f95-8874-0b03dc948afe
      version: -1
      name: Run Comparsion
      description: Takes a snapshot of the operational state of the system.
      script: '|||pan-os-assurance-compare-snapshots'
      type: regular
      iscommand: true
      brand: ""
    scriptarguments:
      left_snapshot_id:
        complex:
          root: File
          accessor: EntryID
          transformers:
          - operator: FirstArrayElement
      right_snapshot_id:
        complex:
          root: File
          accessor: EntryID
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: Snapshot Comparison Result
      output:
        simple: ${FirewallAssurance.SnapshotComparisonResult}
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: b555a0c7-978f-405b-8fa9-01ab8b6f9aca
    type: regular
    task:
      id: b555a0c7-978f-405b-8fa9-01ab8b6f9aca
      version: -1
      name: Save First Snapshot
      description: Copies a file from this incident to the specified incident. The
        file is recorded as an entry in the specified incident’s War Room.
      scriptName: UploadFile
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      body:
        simple: '{"field": "firstsnapshot"}'
      entryID:
        complex:
          root: File
          accessor: EntryID
          transformers:
          - operator: LastArrayElement
      incID:
        simple: ${incident.id}
      target:
        simple: incident attachment
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 70b880e8-1f03-45a1-8b06-9c60215ed597
    type: regular
    task:
      id: 70b880e8-1f03-45a1-8b06-9c60215ed597
      version: -1
      name: Save Second Snapshot
      description: Copies a file from this incident to the specified incident. The
        file is recorded as an entry in the specified incident’s War Room.
      scriptName: UploadFile
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      body:
        simple: '{"field": "secondsnapshot"}'
      entryID:
        complex:
          root: File
          accessor: EntryID
          transformers:
          - operator: LastArrayElement
      incID:
        simple: ${incident.id}
      target:
        simple: incident attachment
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1725,
        "width": 1190,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: target
  value:
    simple: ${incident.panosnetworkoperationsupgradetargetfirewall}
  required: true
  description: Target firewall - helpful if running this playbook in a loop.
  playbookInputQuery: null
outputs: []
