id: 91798901-7d40-4e34-8ecf-1f0119c30b6d
version: 5
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Check if Device Onboarded
description: Checks for the given serial number to validate if it's connected to Panorama.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 268e268c-0a3d-4c99-8a1f-e9b117cfa33d
    type: start
    task:
      id: 268e268c-0a3d-4c99-8a1f-e9b117cfa33d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: cbb8a93d-fc84-48fc-80ba-ec09d087def6
    type: regular
    task:
      id: cbb8a93d-fc84-48fc-80ba-ec09d087def6
      version: -1
      name: Get Device By Serial
      description: Returns indicator custom fields into the context by the given query.
      scriptName: GetIndicatorFieldsByQuery
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      query:
        simple: value:${inputs.serial}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: e1db7e95-9eb9-4db3-8770-7a292d3e8d47
    type: condition
    task:
      id: e1db7e95-9eb9-4db3-8770-7a292d3e8d47
      version: -1
      name: Did we get a firewall?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: GetIndicatorFieldsByQuery
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 1a8e7673-b4f0-4b6c-8b83-72da4a6bedd5
    type: regular
    task:
      id: 1a8e7673-b4f0-4b6c-8b83-72da4a6bedd5
      version: -1
      name: Onboarding Process Complete
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 950
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: c67f74ef-276e-4590-820e-da0097395ae7
    type: regular
    task:
      id: c67f74ef-276e-4590-820e-da0097395ae7
      version: -1
      name: Device not yet connected - reset the timer
      description: commands.local.cmd.reset.timer
      script: Builtin|||resetTimer
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      timerField:
        simple: pauseforpanorama
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 850,
          "y": 580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: d29215d4-f0ed-49b0-8560-4f579ef5e9ef
    type: regular
    task:
      id: d29215d4-f0ed-49b0-8560-4f579ef5e9ef
      version: -1
      name: Associate the device indicator with this onboarding incident.
      description: commands.local.cmd.associate.indicators
      script: Builtin|||associateIndicatorsToIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      incidentId:
        simple: ${incident.id}
      indicatorsValues:
        simple: ${inputs.serial}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 7330b73c-4556-455c-8a45-b4a5d7f2df8a
    type: title
    task:
      id: 7330b73c-4556-455c-8a45-b4a5d7f2df8a
      version: -1
      name: Start the Timer
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 850,
          "y": 785
        }
      }
    note: false
    timertriggers:
    - fieldname: pauseforpanorama
      action: start
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 4e8f9a54-c119-48f5-8639-f40e3f011b3c
    type: regular
    task:
      id: 4e8f9a54-c119-48f5-8639-f40e3f011b3c
      version: -1
      name: Update Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      onboardingstatus:
        simple: Firewall Onboarded
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 995,
        "width": 780,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: serial
  value:
    simple: ${incident.serialnumber}
  required: true
  description: Serial number of FW to check.
  playbookInputQuery: null
outputs: []
