id: PAN-OS Network Operations - Upgrade Assurance - Assurance Test
version: 17
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Upgrade Assurance - Assurance Test
description: Take a second snapshot and finalize the comparison tests.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6252aeba-3f36-4f9b-8d85-3a096bc82e2a
    type: start
    task:
      id: 6252aeba-3f36-4f9b-8d85-3a096bc82e2a
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -90
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: e5f01b41-5722-4c87-a86b-5e96a8a22029
    type: regular
    task:
      id: e5f01b41-5722-4c87-a86b-5e96a8a22029
      version: -1
      name: Take the Second snapshot
      description: Takes a snapshot of the operational state of the system.
      script: PAN_OS_Upgrade_Assurance|||pan-os-assurance-run-snapshot
      type: regular
      iscommand: true
      brand: PAN_OS_Upgrade_Assurance
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      check_list:
        simple: ${alert.snapshotchecklist}
      firewall_serial:
        simple: ${inputs.target}
      snapshot_name:
        simple: second_snapshot
      using:
        simple: ${inputs.AssuranceInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: ee6e434b-e663-4f54-8b02-bd5546c5ab43
    type: regular
    task:
      id: ee6e434b-e663-4f54-8b02-bd5546c5ab43
      version: -1
      name: Run Comparsion
      description: Takes a snapshot of the operational state of the system.
      script: PAN_OS_Upgrade_Assurance|||pan-os-assurance-compare-snapshots
      type: regular
      iscommand: true
      brand: PAN_OS_Upgrade_Assurance
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      left_snapshot_id:
        simple: ${inputs.FirstSnapshotID}
      right_snapshot_id:
        simple: ${File.EntryID}
      using:
        simple: ${inputs.AssuranceInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: Snapshot Comparison Result
      output:
        simple: ${FirewallAssurance.SnapshotComparisonResult}
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: d37b06b9-31ce-4ff7-b19d-2b261ac8df78
    type: regular
    task:
      id: d37b06b9-31ce-4ff7-b19d-2b261ac8df78
      version: -1
      name: Update Report
      description: This script takes the results from readiness checks and/or snapshot
        comparison checks and appends the results in a report format
      scriptName: CreateUpgradeReport
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      existing_report:
        simple: ${alert.upgradeassurancereport}
      snapshot_results:
        simple: ${FirewallAssurance.SnapshotComparisonResult}
      stage:
        simple: PostUpgrade
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 554.375
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: Upgrade Assurance Report
      output:
        simple: ${UpgradeReport}
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: a983adab-1637-459e-8954-100600a2088d
    type: regular
    task:
      id: a983adab-1637-459e-8954-100600a2088d
      version: -1
      name: Clear Context for Looping
      description: "Delete field from context.\n\nThis automation runs using the default
        Limited User role, unless you explicitly change the permissions.\nFor more
        information, see the section about permissions here:\n- For Cortex XSOAR 6
        see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      subplaybook:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 714.375,
        "width": 380,
        "x": 450,
        "y": -90
      }
    }
  }
inputs:
- key: target
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: FirstSnapshotID
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
- key: AssuranceInstance
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
inputSections:
- inputs:
  - target
  - FirstSnapshotID
  - AssuranceInstance
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs: []
  name: General (Outputs group)
  description: Generic group for outputs
outputs: []
dirtyInputs: true
