id: PAN-OS Network Operations - Download Software
version: 5
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Download Software
description: Download PAN-OS System software.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1dfc9fd7-2a39-44c4-842a-393c7d1eeaab
    type: start
    task:
      id: 1dfc9fd7-2a39-44c4-842a-393c7d1eeaab
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -510
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: fbf8f2f4-52af-4756-8dc5-c86e885fcadc
    type: regular
    task:
      id: fbf8f2f4-52af-4756-8dc5-c86e885fcadc
      version: -1
      name: Download the Software Version
      description: Download The provided software version onto the device.
      script: '|||pan-os-platform-download-software'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      retry-count:
        simple: "5"
      retry-interval:
        simple: "60"
      version:
        simple: ${inputs.target_version}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -225
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 663c02c1-97cc-4672-8b24-19e647edc63a
    type: regular
    task:
      id: 663c02c1-97cc-4672-8b24-19e647edc63a
      version: -1
      name: Get Jobs
      description: Get all the jobs from the devices in the environment.
      script: '|||pan-os-platform-get-jobs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      device_filter_string:
        simple: ${PANOS.DownloadStatus.Summary.hostid}
      ignore-outputs:
        simple: "false"
      job_type:
        simple: Downld
      status:
        simple: ACT
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: d572700f-6232-4bac-86f0-5e7c44964c38
    type: playbook
    task:
      id: d572700f-6232-4bac-86f0-5e7c44964c38
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: device_filter_string
      AdditionalPollingCommandArgValues:
        simple: ${inputs.target}
      Ids:
        complex:
          root: PANOS.JobStatus
          accessor: id
          transformers:
          - operator: LastArrayElement
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: id
      PollingCommandName:
        simple: pan-os-platform-get-jobs
      Timeout:
        simple: ${inputs.timeout}
      dt:
        simple: PANOS.JobStatus(val.status!=="FIN").id
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      scriptArguments:
        Ids:
          complex:
            root: PANOS.JobStatus
            accessor: id
            transformers:
            - operator: LastArrayElement
        Interval:
          simple: "1"
        PollingCommandArgName:
          simple: id
        PollingCommandName:
          simple: pan-os-platform-get-jobs
        Timeout:
          simple: "30"
        dt:
          simple: PANOS.JobStatus(val.status!=="FIN").id
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 440,
          "y": 670
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 392df7c5-9e23-4d79-8d97-6d47fe00a90f
    type: regular
    task:
      id: 392df7c5-9e23-4d79-8d97-6d47fe00a90f
      version: -1
      name: Get jobs again to check status
      description: Get all the jobs from the devices in the environment, or a single
        job when ID is specified.
      script: '|||pan-os-platform-get-jobs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      id:
        complex:
          root: PANOS.JobStatus
          accessor: id
          transformers:
          - operator: LastArrayElement
      target:
        simple: ${inputs.target}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 96c2e42b-b178-4fae-8e2b-03ccb22d2e29
    type: condition
    task:
      id: 96c2e42b-b178-4fae-8e2b-03ccb22d2e29
      version: -1
      name: Did it complete?
      description: True if the software download was successful
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.JobStatus.status
            iscontext: true
          right:
            value:
              simple: FIN
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.JobStatus.result
            iscontext: true
          right:
            value:
              simple: OK
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: e1df68ac-44dc-4864-8f70-9dbc5913c580
    type: title
    task:
      id: e1df68ac-44dc-4864-8f70-9dbc5913c580
      version: -1
      name: Finish
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 046550c2-051f-4e7c-833b-c33dd8e64738
    type: regular
    task:
      id: 046550c2-051f-4e7c-833b-c33dd8e64738
      version: -1
      name: Fail message
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Download job failed.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 870,
          "y": 1165
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 647541b5-204c-4c8f-8f56-793141f89be0
    type: regular
    task:
      id: 647541b5-204c-4c8f-8f56-793141f89be0
      version: -1
      name: Set Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      description:
        simple: Downloading Software Version ${inputs.target_version}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": -390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 4997d532-34c2-4434-8f57-9a5182059d13
    type: regular
    task:
      id: 4997d532-34c2-4434-8f57-9a5182059d13
      version: -1
      name: Wait for job to get processed
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      seconds:
        simple: "30"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 9116bad2-5564-4993-8d25-ba63bf931c9a
    type: condition
    task:
      id: 9116bad2-5564-4993-8d25-ba63bf931c9a
      version: -1
      name: Did we get a job?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: PANOS.JobStatus.id
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 0cf3fc4c-c616-4614-86ec-f657ba3eb6ba
    type: regular
    task:
      id: 0cf3fc4c-c616-4614-86ec-f657ba3eb6ba
      version: -1
      name: Get Jobs
      description: Get all the jobs from the devices in the environment.
      script: '|||pan-os-platform-get-jobs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      device_filter_string:
        simple: ${PANOS.DownloadStatus.Summary.hostid}
      ignore-outputs:
        simple: "false"
      job_type:
        simple: Downld
      status:
        simple: ACT
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1770,
        "width": 850,
        "x": 440,
        "y": -510
      }
    }
  }
inputs:
- key: target
  value: {}
  required: false
  description: Target Firewall - Serial or IP address
  playbookInputQuery: null
- key: target_version
  value: {}
  required: false
  description: Target Software Version to Download
  playbookInputQuery: null
- key: timeout
  value:
    simple: "45"
  required: false
  description: Default max timeout value
  playbookInputQuery: null
outputs: []
