id: PAN-OS Network Operations - Onboarding
version: 5
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Onboarding
description: Onboards the NGFW and Panorama devices as XSOAR incidents.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 38507585-4eea-4480-83bf-e3115c544879
    type: start
    task:
      id: 38507585-4eea-4480-83bf-e3115c544879
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: a4d0e4e7-90f2-48d6-8a49-76f30103a34f
    type: regular
    task:
      id: a4d0e4e7-90f2-48d6-8a49-76f30103a34f
      version: -1
      name: Update device incidents
      description: Given a target device, creates or updates an existing PAN-OS Network
        Operations - Device incident.
      scriptName: CreateOrUpdateDeviceIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      target:
        simple: ${PANOS.ShowSystemInfo.Summary.hostid}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: e6660bae-a855-4c39-840a-5829e0763426
    type: regular
    task:
      id: e6660bae-a855-4c39-840a-5829e0763426
      version: -1
      name: Get system information
      description: Gets information from all PAN-OS systems in the topology.
      script: '|||pan-os-platform-get-system-info'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 706c2c07-d528-436a-857c-f956c45f84d9
    type: regular
    task:
      id: 706c2c07-d528-436a-857c-f956c45f84d9
      version: -1
      name: Link Incidents
      description: commands.local.cmd.linkIncidents
      script: Builtin|||linkIncidents
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      linkedIncidentIDs:
        simple: ${DeviceIncidents.device_incident_id}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 530
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 928e2b9a-e538-42cc-89a5-80cdf5970a9b
    type: title
    task:
      id: 928e2b9a-e538-42cc-89a5-80cdf5970a9b
      version: -1
      name: Onboarding Finished
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 725,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
