id: PAN-OS Network Operations - Domain Upgrade
version: 64
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Batch Upgrade
description: |-
  This playbook uses XQL to query the devices to be upgraded.  It will create a separate alert for each device found by the XQL query.

  The following alert fields are required and will be prompted to be set if missing:
   - PAN-OS Network Operations - Automatic Upgrade (defaults to False)
   - PAN-OS Network Operations - Target NGFW Software (for NGFW upgrades)
   - PAN-OS Network Operations - Target Panorama Software (for Panorama upgrades)
   - PAN-OS Network Operations - XQL (to identify the devices to upgrade)
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 746f36df-f75a-4aaa-8861-21e784000036
    type: start
    task:
      id: 746f36df-f75a-4aaa-8861-21e784000036
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 334.5,
          "y": 1369
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: b92124cd-7a65-43fb-b328-5450d3070710
    type: title
    task:
      id: b92124cd-7a65-43fb-b328-5450d3070710
      version: -1
      name: Create Panorama Upgrade Alerts
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "41"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 2090
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 696de99e-7ff2-41c7-9ac3-bb156815ce39
    type: regular
    task:
      id: 696de99e-7ff2-41c7-9ac3-bb156815ce39
      version: -1
      name: Create Panorama Incidents
      description: Uses the core-api generic POST integration command to create upgrade
        alerts for each device.
      scriptName: CreateFWUpgradeAlerts
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "46"
    scriptarguments:
      DeviceType:
        simple: Panorama
      Playbook:
        simple: ${alert.panosnetworkoperationsbatchplaybook}
      TargetDevices:
        simple: ${PanoramaDevices}
      TargetVersion:
        simple: ${alert.panosnetworkoperationstargetpanoramasoftware}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 699,
          "y": 2687
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: 80a832a1-8431-4b9b-af08-e22bffdb6c03
    type: regular
    task:
      id: 80a832a1-8431-4b9b-af08-e22bffdb6c03
      version: -1
      name: Create Firewall Incidents
      description: Uses the core-api generic POST integration command to create upgrade
        alerts for each device.
      scriptName: CreateFWUpgradeAlerts
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      DeviceType:
        simple: NGFW
      Playbook:
        simple: ${alert.panosnetworkoperationsbatchplaybook}
      TargetDevices:
        simple: ${NGFWDevices}
      TargetVersion:
        simple: ${alert.panosnetworkoperationstargetngfwsoftware}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 675,
          "y": 3669
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: 697abded-5fb5-480f-8147-113b2bfa1206
    type: regular
    task:
      id: 697abded-5fb5-480f-8147-113b2bfa1206
      version: -1
      name: Delete context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "53"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 334.5,
          "y": 1507
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "25":
    id: "25"
    taskid: c2806aa9-41eb-4881-801c-e589b3eb612e
    type: title
    task:
      id: c2806aa9-41eb-4881-801c-e589b3eb612e
      version: -1
      name: Start Upgrade Process Per Alert
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "30"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 343.5,
          "y": 3813
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "30":
    id: "30"
    taskid: 3ce00018-5e25-44ba-9d3a-63012e4a9b80
    type: playbook
    task:
      id: 3ce00018-5e25-44ba-9d3a-63012e4a9b80
      version: -1
      name: PAN-OS Network Operations - Start Device Upgrades
      description: |-
        This playbook is used by the Domain Upgrade playbook to start (either manually or automatically) groups of Device Upgrade incidents.

        It works by first retrieving the administrative domains/device-groups that have upgrades pending, then marking the pause tasks within them complete in batches.
      playbookName: PAN-OS Network Operations - Start Device Upgrades
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "31"
    scriptarguments:
      Automatically Upgrade:
        simple: ${alert.panosnetworkoperationsautomaticupgrade}
      NGFWDevices:
        simple: ${NGFWDevices}
      PanoramaDevices:
        simple: ${PanoramaDevices}
      alert_ids:
        complex:
          root: CreatedAlertIDs
          accessor: NGFW
          transformers:
          - operator: append
            args:
              item:
                value:
                  simple: CreatedAlertIDs.Panorama
                iscontext: true
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 343.5,
          "y": 3943
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "31":
    id: "31"
    taskid: 118bfdae-bd45-4824-be57-138df27de44e
    type: regular
    task:
      id: 118bfdae-bd45-4824-be57-138df27de44e
      version: -1
      name: Close Alert
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "32"
    scriptarguments:
      closeNotes:
        simple: This upgrade incident has been closed - all devices are now upgrading,
          and can be monitored by looking either at the PAN-OS Network Operations
          dashboard or the individual alerts directly.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 343.5,
          "y": 4110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "32":
    id: "32"
    taskid: 6906bff5-3ebe-47ff-ada0-7ce2be14c3f6
    type: title
    task:
      id: 6906bff5-3ebe-47ff-ada0-7ce2be14c3f6
      version: -1
      name: DONE
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 343.5,
          "y": 4281
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "41":
    id: "41"
    taskid: 5282b2eb-cfb3-4a7e-9550-40e18e4b978d
    type: condition
    task:
      id: 5282b2eb-cfb3-4a7e-9550-40e18e4b978d
      version: -1
      name: Are there Panorama Devices?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "50"
      "yes":
      - "42"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: ${PanoramaDevices}
            iscontext: true
          ignorecase: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 2247
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "42":
    id: "42"
    taskid: f422d784-f474-4992-9543-06cd5fbd14bc
    type: playbook
    task:
      id: f422d784-f474-4992-9543-06cd5fbd14bc
      version: -1
      name: PAN-OS Network Operations - Software Select
      description: Checks to validate that a version (if provided) is valid for upgrade
      playbookName: PAN-OS Network Operations - Software Select
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "45"
    scriptarguments:
      PanoramaInstance:
        simple: ${PanoramaInstance}
      TargetDevice:
        simple: ${PanoramaDevices}
      TargetVersion:
        simple: ${alert.panosnetworkoperationstargetpanoramasoftware}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 699,
          "y": 2399
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "45":
    id: "45"
    taskid: dcf5f15e-7ca1-4288-a670-5c52c6d4ce1a
    type: regular
    task:
      id: dcf5f15e-7ca1-4288-a670-5c52c6d4ce1a
      version: -1
      name: Set Panorama Target Version
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      panosnetworkoperationstargetpanoramasoftware:
        simple: ${TargetVersion}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 699,
          "y": 2535
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "46":
    id: "46"
    taskid: 850e8cd0-b98b-45f6-b831-5faf967cf4af
    type: regular
    task:
      id: 850e8cd0-b98b-45f6-b831-5faf967cf4af
      version: -1
      name: Cleanup Context
      description: "Delete field from context.\n\nThis automation runs using the default
        Limited User role, unless you explicitly change the permissions.\nFor more
        information, see the section about permissions here:\n- For Cortex XSOAR 6
        see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "50"
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: PANOS, TargetVersion
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 701,
          "y": 2827
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "47":
    id: "47"
    taskid: dcd14b8e-6581-4f3e-82ba-e762ba5920ff
    type: condition
    task:
      id: dcd14b8e-6581-4f3e-82ba-e762ba5920ff
      version: -1
      name: Are there Firewall Devices?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "25"
      "yes":
      - "49"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: ${NGFWDevices}
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 343.5,
          "y": 3158
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "49":
    id: "49"
    taskid: d7c6cfa0-d874-4f8e-af56-72924a685446
    type: playbook
    task:
      id: d7c6cfa0-d874-4f8e-af56-72924a685446
      version: -1
      name: PAN-OS Network Operations - Software Select
      description: Checks to validate that a version (if provided) is valid for upgrade
      playbookName: PAN-OS Network Operations - Software Select
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "51"
    scriptarguments:
      PanoramaInstance:
        simple: ${PanoramaInstance}
      TargetDevice:
        simple: ${NGFWDevices}
      TargetVersion:
        simple: ${alert.panosnetworkoperationstargetngfwsoftware}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 675,
          "y": 3344
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "50":
    id: "50"
    taskid: 200970ab-be0b-40a3-b3a0-686898befa3c
    type: title
    task:
      id: 200970ab-be0b-40a3-b3a0-686898befa3c
      version: -1
      name: Create Firewall Upgrade Alerts
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "47"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 343.5,
          "y": 3005
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "51":
    id: "51"
    taskid: d9d6523e-27f5-49d2-b0df-58c774d98b33
    type: regular
    task:
      id: d9d6523e-27f5-49d2-b0df-58c774d98b33
      version: -1
      name: Set FW Target Version
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      panosnetworkoperationstargetngfwsoftware:
        simple: ${TargetVersion}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 675,
          "y": 3498
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "53":
    id: "53"
    taskid: 09a2a082-1a29-4902-80a8-fe281b1b6272
    type: playbook
    task:
      id: 09a2a082-1a29-4902-80a8-fe281b1b6272
      version: -1
      name: PAN-OS Network Operations - Query Devices
      playbookName: PAN-OS Network Operations - Query Devices
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "54"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 334.5,
          "y": 1680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "54":
    id: "54"
    taskid: bb7fd277-3c1f-4413-adb9-ff77cd537a23
    type: condition
    task:
      id: bb7fd277-3c1f-4413-adb9-ff77cd537a23
      version: -1
      name: Any Errors from Query?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "31"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Errors
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 53,
          "y": 1864
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "41_42_yes": 0.49,
      "41_50_#default#": 0.26,
      "47_25_#default#": 0.1,
      "54_31_yes": 0.1,
      "54_4_#default#": 0.52
    },
    "paper": {
      "dimensions": {
        "height": 2972,
        "width": 1028,
        "x": 53,
        "y": 1369
      }
    }
  }
inputs: []
inputSections:
- inputs: []
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs: []
  name: General (Outputs group)
  description: Generic group for outputs
outputs: []
dirtyInputs: true
