id: be9dfaa4-a371-4b46-8088-67679944a38b
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Take Snapshot
description: Takes a JSON snapshot of the current operational state of the device.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3c099c56-a0a8-4b34-8db4-2fc5651f59f2
    type: start
    task:
      id: 3c099c56-a0a8-4b34-8db4-2fc5651f59f2
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: e4bc6635-26d1-44b0-86ca-0397cf9f00c8
    type: regular
    task:
      id: e4bc6635-26d1-44b0-86ca-0397cf9f00c8
      version: -1
      name: Take Snapshot
      description: Takes a JSON Snapshot of the current operational state of the target
        device
      tags:
      - snapshot-file
      scriptName: TakeOperationalSnapshot
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      target:
        simple: ${inputs.target}
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
    note: true
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 528d4ffe-bece-4be5-89ee-fcc26e9e62f2
    type: title
    task:
      id: 528d4ffe-bece-4be5-89ee-fcc26e9e62f2
      version: -1
      name: Finish
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 570
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 78c2ac0a-c996-42e2-87b3-c65000ca72a5
    type: regular
    task:
      id: 78c2ac0a-c996-42e2-87b3-c65000ca72a5
      version: -1
      name: Set Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      description:
        simple: Taking System Snapshot
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 585,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: target
  value:
    simple: ${incident.panosnetworkoperationstarget}
  required: true
  description: The target to take the snapshot of
  playbookInputQuery: null
outputs:
- contextPath: File.EntryID
  description: The file entry ID.
  type: string
quiet: true
