id: be9dfaa4-a371-4b46-8088-67679944a38b
version: 5
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Take Snapshot
description: Takes a JSON snapshot of the current operational state of the device.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: cbdef3f2-f531-4a35-8f05-1e3c184ff55e
    type: start
    task:
      id: cbdef3f2-f531-4a35-8f05-1e3c184ff55e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: edbb18e0-483b-496a-8c2c-f7b2e34985cf
    type: regular
    task:
      id: edbb18e0-483b-496a-8c2c-f7b2e34985cf
      version: -1
      name: Take Snapshot
      description: Takes a JSON Snapshot of the current operational state of the target
        device
      tags:
      - snapshot-file
      scriptName: TakeOperationalSnapshot
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      target:
        simple: ${inputs.target}
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
    note: true
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 65eccdae-3d4a-4cc7-8fe5-b120327647dd
    type: title
    task:
      id: 65eccdae-3d4a-4cc7-8fe5-b120327647dd
      version: -1
      name: Finish
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 570
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 69232190-02bd-40c0-84c9-0b50eb30485d
    type: regular
    task:
      id: 69232190-02bd-40c0-84c9-0b50eb30485d
      version: -1
      name: Set Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      description:
        simple: Taking System Snapshot
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 585,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: target
  value:
    simple: ${incident.panosnetworkoperationstarget}
  required: true
  description: The target to take the snapshot of
  playbookInputQuery: null
outputs:
- contextPath: File.EntryID
  description: The file entry ID.
  type: string
quiet: true
