id: PAN-OS Network Operations - Single Device Upgrade
version: 11
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Single Device Upgrade
description: Runs a complete upgrade process for a single device
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 7a552bab-bd8b-47cc-89a3-cde155e429c2
    type: start
    task:
      id: 7a552bab-bd8b-47cc-89a3-cde155e429c2
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "41"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1755
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 5b752e99-056d-473a-a615-765aa75b1599
    type: regular
    task:
      id: 5b752e99-056d-473a-a615-765aa75b1599
      version: -1
      name: Reboot the system
      description: |
        Reboots the given device by host ID. Warning: This command has no confirmation and the device will immediately reboot. This command can be disruptive.
      script: Panorama|||pan-os-platform-reboot
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      target:
        simple: ${inputs.target}
      using:
        simple: ${inputs.PanoramaInstance}
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -65
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 3958b0b0-1f77-48b4-93ea-47b2e5fce996
    type: playbook
    task:
      id: 3958b0b0-1f77-48b4-93ea-47b2e5fce996
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.

        NOTE: This playbook should be run only when the playbook's context is using the "Private to sub-playbook" option.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: using
      AdditionalPollingCommandArgValues:
        simple: ${inputs.PanoramaInstance}
      Ids:
        simple: ${inputs.target}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: target
      PollingCommandName:
        simple: pan-os-platform-get-system-status
      Timeout:
        simple: "60"
      dt:
        simple: PANOS.SystemStatus(!val.up).hostid
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      scriptArguments:
        AdditionalPollingCommandArgNames:
          simple: using
        AdditionalPollingCommandArgValues:
          simple: ${incident.panosnetworkoperationspanoramainstance}
        Ids:
          simple: ${inputs.target}
        Interval:
          simple: "1"
        PollingCommandArgName:
          simple: target
        PollingCommandName:
          simple: pan-os-platform-get-system-status
        Timeout:
          simple: "60"
        dt:
          simple: PANOS.SystemStatus(!val.up).hostid
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 82f8a7c4-7a2e-426f-80eb-6f0fda66a654
    type: title
    task:
      id: 82f8a7c4-7a2e-426f-80eb-6f0fda66a654
      version: -1
      name: Finish
      description: Finish
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 825
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: 2173a52d-eab8-4ef8-815f-215714adb848
    type: regular
    task:
      id: 2173a52d-eab8-4ef8-815f-215714adb848
      version: -1
      name: Get System Info
      description: Gets information from all PAN-OS systems in the topology.
      script: Panorama|||pan-os-platform-get-system-info
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      using:
        simple: ${inputs.PanoramaInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: 8a9c196a-87d8-439a-853b-eeb34189fcc5
    type: condition
    task:
      id: 8a9c196a-87d8-439a-853b-eeb34189fcc5
      version: -1
      name: Check System running new version
      description: Checks whether the post-upgrade software version is correct.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "20"
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: PANOS.ShowSystemInfo.Result.sw_version
            iscontext: true
          right:
            value:
              simple: inputs.target_version
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: 4e5b5934-2a7d-4b4b-8373-3a237b5732d9
    type: regular
    task:
      id: 4e5b5934-2a7d-4b4b-8373-3a237b5732d9
      version: -1
      name: Fail message
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Installation completed, reboot completed, but device still on old
          software version.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 810
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: 6d407db1-3ec5-4f5a-8462-30ba4cef1a60
    type: regular
    task:
      id: 6d407db1-3ec5-4f5a-8462-30ba4cef1a60
      version: -1
      name: Sleep to let device shutdown gracefully
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      seconds:
        simple: "25"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "22":
    id: "22"
    taskid: 0a0e29e9-d28e-4b04-91fa-6832ffa39be0
    type: regular
    task:
      id: 0a0e29e9-d28e-4b04-91fa-6832ffa39be0
      version: -1
      name: Get Available Software
      description: Checks the devices for software that is available to be installed.
      script: Panorama|||pan-os-platform-get-available-software
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "35"
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      using:
        simple: ${inputs.PanoramaInstance}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1460
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "23":
    id: "23"
    taskid: 870fc64d-0d5d-4b5e-8327-0134a994d31f
    type: condition
    task:
      id: 870fc64d-0d5d-4b5e-8327-0134a994d31f
      version: -1
      name: Has the software already been downloaded?
      description: Checks if the upgrade software version is already downloaded onto
        the PAN-OS system.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "38"
      "yes":
      - "39"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              complex:
                root: PANOS.SoftwareVersions.Summary
                filters:
                - - operator: isTrue
                    left:
                      value:
                        simple: PANOS.SoftwareVersions.Summary.downloaded
                      iscontext: true
                accessor: version
            iscontext: true
          right:
            value:
              simple: inputs.target_version
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "27":
    id: "27"
    taskid: 65106ac9-a9ed-42ce-8b68-db9ae2ad74cf
    type: condition
    task:
      id: 65106ac9-a9ed-42ce-8b68-db9ae2ad74cf
      version: -1
      name: Is the base version of this image downloaded?
      description: True if the base version of the upgrade image is downloaded.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "37"
      "yes":
      - "23"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: in
          left:
            value:
              simple: BaseImage
            iscontext: true
          right:
            value:
              complex:
                root: PANOS.SoftwareVersions.Summary
                filters:
                - - operator: isTrue
                    left:
                      value:
                        simple: PANOS.SoftwareVersions.Summary.downloaded
                      iscontext: true
                accessor: version
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "35":
    id: "35"
    taskid: 2dc06081-87fd-4ad7-83f2-df8d4b4eebd8
    type: regular
    task:
      id: 2dc06081-87fd-4ad7-83f2-df8d4b4eebd8
      version: -1
      name: Set BASE Software Version
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      key:
        simple: BaseImage
      value:
        complex:
          root: inputs.target_version
          transformers:
          - operator: split
            args:
              delimiter:
                value:
                  simple: .
          - operator: slice
            args:
              from:
                value:
                  simple: "0"
              to:
                value:
                  simple: "2"
          - operator: join
            args:
              separator:
                value:
                  simple: .
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: ".0"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "37":
    id: "37"
    taskid: 930c2cc2-3930-4c88-aec7-e0ee30d2cb2e
    type: playbook
    task:
      id: 930c2cc2-3930-4c88-aec7-e0ee30d2cb2e
      version: -1
      name: PAN-OS Network Operations - Download Software
      description: Download PAN-OS System software.
      playbookName: PAN-OS Network Operations - Download Software
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      PanoramaInstance:
        simple: ${inputs.PanoramaInstance}
      target:
        simple: ${inputs.target}
      target_version:
        simple: ${BaseImage}
      timeout:
        simple: "45"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 690,
          "y": -930
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "38":
    id: "38"
    taskid: 39b9e638-4d30-4f6b-a15f-a2973f658115
    type: playbook
    task:
      id: 39b9e638-4d30-4f6b-a15f-a2973f658115
      version: -1
      name: PAN-OS Network Operations - Download Software
      description: Download PAN-OS System software.
      playbookName: PAN-OS Network Operations - Download Software
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "39"
    scriptarguments:
      PanoramaInstance:
        simple: ${inputs.PanoramaInstance}
      target:
        simple: ${inputs.target}
      target_version:
        simple: ${inputs.target_version}
      timeout:
        simple: "45"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 690,
          "y": -565
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "39":
    id: "39"
    taskid: 2ee5132b-dc25-4767-a129-d8d6b88dc968
    type: playbook
    task:
      id: 2ee5132b-dc25-4767-a129-d8d6b88dc968
      version: -1
      name: PAN-OS Network Operations - Install Software
      description: Installs PAN-OS system software.
      playbookName: PAN-OS Network Operations - Install Software
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "40"
    scriptarguments:
      PanoramaInstance:
        simple: ${inputs.PanoramaInstance}
      target:
        simple: ${inputs.target}
      target_version:
        simple: ${inputs.target_version}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 450,
          "y": -375
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "40":
    id: "40"
    taskid: cd7a5657-7397-4070-a042-0469b6db2971
    type: regular
    task:
      id: cd7a5657-7397-4070-a042-0469b6db2971
      version: -1
      name: Set Status
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      details:
        simple: Rebooting ${inputs.target}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "41":
    id: "41"
    taskid: ca4d4862-cf59-4a5a-8b11-c7086f39ffa9
    type: regular
    task:
      id: ca4d4862-cf59-4a5a-8b11-c7086f39ffa9
      version: -1
      name: Clear Context for Looping
      description: "Delete field from context.\n\nThis automation runs using the default
        Limited User role, unless you explicitly change the permissions.\nFor more
        information, see the section about permissions here:\n- For Cortex XSOAR 6
        see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      all:
        simple: "yes"
      subplaybook:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1625
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "23_38_#default#": 0.64
    },
    "paper": {
      "dimensions": {
        "height": 2640,
        "width": 840,
        "x": 450,
        "y": -1755
      }
    }
  }
inputs:
- key: target
  value: {}
  required: true
  description: Target firewall to upgrade
  playbookInputQuery: null
- key: target_version
  value: {}
  required: true
  description: Target version to upgrade to.
  playbookInputQuery: null
- key: PanoramaInstance
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
inputSections:
- inputs:
  - target
  - target_version
  - PanoramaInstance
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs: []
  name: General (Outputs group)
  description: Generic group for outputs
outputs: []
dirtyInputs: true
