id: 281f55fa-ba0c-4a98-8a36-3bc0c35c8472
version: 16
vcShouldKeepItemLegacyProdMachine: false
name: PAN-OS Network Operations - Upgrade Assurance - First Snapshot
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b5f9b4a7-2c71-402c-81f5-fe82c791f092
    type: start
    task:
      id: b5f9b4a7-2c71-402c-81f5-fe82c791f092
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 759ad744-d5e3-4bb3-83ee-20ccd3627814
    type: regular
    task:
      id: 759ad744-d5e3-4bb3-83ee-20ccd3627814
      version: -1
      name: Run Readiness Tests
      description: Runs checks to confirm a PAN-OS firewall is ready to be upgraded.
      script: '|||pan-os-assurance-run-readiness-checks'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "9"
    scriptarguments:
      arp_entry_exists:
        simple: ${incident.checkarpentryexists}
      candidate_version:
        simple: ${incident.panosnetworkoperationsupgradetargetfirewallversion}
      check_list:
        simple: ${incident.readinesschecklist}
      check_session_exists:
        simple: ${incident.checksessionexists}
      firewall_serial:
        simple: ${inputs.target}
      min_content_version:
        simple: ${incident.minimumcontentversion}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    fieldMapping:
    - incidentfield: Readiness Check Result
      output:
        complex:
          root: FirewallAssurance
          accessor: ReadinessCheckResults
          transformers:
          - operator: ConvertKeysToTableFieldFormat
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: b6f607b6-1491-421a-840d-6899e4b8a1ef
    type: condition
    task:
      id: b6f607b6-1491-421a-840d-6899e4b8a1ef
      version: -1
      name: Did we get failed tests?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: incident.readinesscheckresult.state
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: incident.readinesscheckresult.state
                      iscontext: true
                    right:
                      value:
                        simple: "false"
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: dbe6028c-a182-48b4-885b-78adb12380a5
    type: collection
    task:
      id: dbe6028c-a182-48b4-885b-78adb12380a5
      version: -1
      name: Failed Readiness Test Confirmation
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: ${incident.owner}
      subject:
        simple: Upgrade Readiness Checks failed on ${incident.panosnetworkoperationsupgradetargetfirewall}
      body:
        simple: "The assurance process failed on the device ${incident.panosnetworkoperationsupgradetargetfirewall}.\n\nPlease
          validate the test result and choose whether to proceed or abort the assurance
          process. "
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: |-
            ### Do you want to continue?
            *Choosing Yes will continue with the upgrade assurance process, and if no other issues are present, the upgrade process itself.*
        required: true
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      title: Failed Readiness Test Confirmation
      description: The assurance process identified issues that might prevent the
        software upgrade from starting. Please confirm whether to proceed or abort
        the assurance process.
      sender: Your SOC team
      expired: false
      totalanswers: 0
    formDisplay:
      headerbackgroundcolor: '#ff0000'
      headerfontcolor: ""
      sender: ""
      bodybackgroundcolor: ""
      bodyfontcolor: ""
      submitbuttonbackgroundcolor: '#f50057'
      submitbuttonfontcolor: ""
      submittext: ""
      isexternalrtl: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: b370c5bd-e767-4707-8c0a-c71e494b6ed2
    type: condition
    task:
      id: b370c5bd-e767-4707-8c0a-c71e494b6ed2
      version: -1
      name: Continue?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Failed Readiness Test Confirmation.Answers.0
            iscontext: true
          right:
            value:
              simple: "Yes"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 940
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 32476526-6d69-48d3-83ab-4d0b5d22d58f
    type: regular
    task:
      id: 32476526-6d69-48d3-83ab-4d0b5d22d58f
      version: -1
      name: Take the first device snapshot
      description: Takes a snapshot of the operational state of the system.
      script: '|||pan-os-assurance-run-snapshot'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      firewall_serial:
        simple: ${inputs.target}
      snapshot_name:
        simple: first_snapshot
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: c3f8eff5-99e9-4226-87f5-a7af67d97870
    type: regular
    task:
      id: c3f8eff5-99e9-4226-87f5-a7af67d97870
      version: -1
      name: Save First Snapshot
      description: Copies a file from this incident to the specified incident. The
        file is recorded as an entry in the specified incident’s War Room.
      scriptName: UploadFile
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      body:
        simple: '{"field": "firstsnapshot"}'
      entryID:
        complex:
          root: File
          accessor: EntryID
          transformers:
          - operator: LastArrayElement
      incID:
        simple: ${incident.id}
      target:
        simple: incident attachment
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 1e00e1f8-3b98-4fa8-8d28-8b85bef4ea9e
    type: regular
    task:
      id: 1e00e1f8-3b98-4fa8-8d28-8b85bef4ea9e
      version: -1
      name: Aborted process.
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      description:
        simple: Assurance testing aborted.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 1290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 0cc1e535-5d2a-4b13-845b-abf1bc722205
    type: regular
    task:
      id: 0cc1e535-5d2a-4b13-845b-abf1bc722205
      version: -1
      name: Update Report
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      upgradeassurancereport:
        simple: |
          # Upgrade Assurance Report

          ## Readiness checks FAILED

          ${incident.readinesscheckresult(val.state=='false')=>x(val);
              function x(v) {
                  s = ""
                  if (v.length == 0) {
                      return "✅ All Tests Passing! ✅";
                  }
                  v.forEach(function(item){
                      s = s + " * ❌ " + item.test + "\n";
                  })
                  return s;
              };
          }

          ## Readiness checks PASSED

          ${incident.readinesscheckresult(val.state=='true')=>x(val);
              function x(v) {
                  s = ""
                  if (v.length == 0) {
                      return "❌ All tests failing! ❌";
                  }
                  v.forEach(function(item){
                      s = s + " * " + item.test + "\n";
                  })
                  return s;
              };
          }
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 30,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 27b9ce61-cf1c-4f1d-8135-b95ecb1c025a
    type: title
    task:
      id: 27b9ce61-cf1c-4f1d-8135-b95ecb1c025a
      version: -1
      name: "YES"
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
      - "11"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 860,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 02837b8b-c2b5-4d60-84ac-9f555ca29bc4
    type: regular
    task:
      id: 02837b8b-c2b5-4d60-84ac-9f555ca29bc4
      version: -1
      name: Set Failed State
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      readinesstestresult:
        simple: Failed ❌
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1270,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 0b69af8d-2fe8-4ff8-89ce-2ef84b6f8619
    type: title
    task:
      id: 0b69af8d-2fe8-4ff8-89ce-2ef84b6f8619
      version: -1
      name: "No"
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: f67890de-cee4-4281-8e65-6601f503875b
    type: regular
    task:
      id: f67890de-cee4-4281-8e65-6601f503875b
      version: -1
      name: Set Passed State
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      readinesstestresult:
        simple: Passed ✅
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1345,
        "width": 1620,
        "x": 30,
        "y": 50
      }
    }
  }
inputs:
- key: target
  value:
    simple: ${incident.panosnetworkoperationstarget}
  required: false
  description: ""
  playbookInputQuery: null
outputs: []
quiet: true
