description: Installs PAN-OS system software.
id: PAN-OS Network Operations - Install Software
inputs:
- description: Target Version to INstall
  key: target_version
  playbookInputQuery: null
  required: false
  value: {}
- description: Target Device
  key: target
  playbookInputQuery: null
  required: false
  value: {}
name: PAN-OS Network Operations - Install Software
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3da9278d-d2f5-4fae-835c-d6e2707bba7a
      iscommand: false
      name: ""
      version: -1
    taskid: 3da9278d-d2f5-4fae-835c-d6e2707bba7a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -80
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      version:
        simple: ${inputs.target_version}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Install the given software version onto the device. Download the
        software first with
      id: e2058e2d-b77d-4411-8d6e-8c6f22202e8d
      iscommand: true
      name: Install the given software version
      script: '|||pan-os-platform-install-software'
      type: regular
      version: -1
    taskid: e2058e2d-b77d-4411-8d6e-8c6f22202e8d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      job_type:
        simple: SWInstall
      status:
        simple: ACT
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get all the jobs from the devices in the environment.
      id: cf1a5176-d615-4b13-85b3-5ebf81e9d0de
      iscommand: true
      name: Get Jobs
      script: '|||pan-os-platform-get-jobs'
      type: regular
      version: -1
    taskid: cf1a5176-d615-4b13-85b3-5ebf81e9d0de
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 340
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      scriptArguments:
        Ids:
          complex:
            accessor: id
            root: PANOS.JobStatus
            transformers:
            - operator: LastArrayElement
        Interval:
          simple: "1"
        PollingCommandArgName:
          simple: id
        PollingCommandName:
          simple: pan-os-platform-get-jobs
        Timeout:
          simple: "20"
        dt:
          simple: PANOS.JobStatus(val.status!=="FIN").id
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: device_filter_string
      AdditionalPollingCommandArgValues:
        simple: ${inputs.target}
      Ids:
        complex:
          accessor: id
          root: PANOS.JobStatus
          transformers:
          - operator: LastArrayElement
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: id
      PollingCommandName:
        simple: pan-os-platform-get-jobs
      Timeout:
        simple: "20"
      dt:
        simple: PANOS.JobStatus(val.status!=="FIN").id
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: a49ad1ec-5e5d-4a51-8fe8-30f888371489
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: a49ad1ec-5e5d-4a51-8fe8-30f888371489
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 650
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: status
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: PANOS.JobStatus.type
                    operator: isEqualString
                    right:
                      value:
                        simple: SWInstall
                root: PANOS.JobStatus
          operator: isEqualString
          right:
            value:
              simple: FIN
      - - left:
            iscontext: true
            value:
              complex:
                accessor: result
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: PANOS.JobStatus.type
                    operator: isEqualString
                    right:
                      value:
                        simple: SWInstall
                root: PANOS.JobStatus
          operator: isEqualString
          right:
            value:
              simple: OK
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the software installation finished successfully.
      id: 288aba5d-bc71-438b-8b1f-0f2debd2b737
      iscommand: false
      name: Did it complete?
      type: condition
      version: -1
    taskid: 288aba5d-bc71-438b-8b1f-0f2debd2b737
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 970
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      id:
        complex:
          accessor: id
          root: PANOS.JobStatus
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get all the jobs from the devices in the environment, or a single
        job when ID is specified.
      id: eab23dcf-5ba1-40e1-8537-f36326acebc5
      iscommand: true
      name: Get jobs again to check status
      script: '|||pan-os-platform-get-jobs'
      type: regular
      version: -1
    taskid: eab23dcf-5ba1-40e1-8537-f36326acebc5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 815
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PANOS.JobStatus.status
          operator: isEqualString
          right:
            value:
              simple: ACT
      label: ACT
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PANOS.JobStatus.status
          operator: isEqualString
          right:
            value:
              simple: FIN
      label: FIN
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      ACT:
      - "3"
      FIN:
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: It's possible that, if software has already been installed, then
        we don't get an active job for it.
      id: 504ca5e2-92b4-4147-89b6-e602ade25fd3
      iscommand: false
      name: Is the job active?
      type: condition
      version: -1
    taskid: 504ca5e2-92b4-4147-89b6-e602ade25fd3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 490
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5e9129f3-3e35-417d-8ecc-7de0135741ad
      iscommand: false
      name: Finish
      type: title
      version: -1
    taskid: 5e9129f3-3e35-417d-8ecc-7de0135741ad
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1160
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: Software install job failed.
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints an error entry with a given message
      id: 3b5432ce-c08c-4bfa-8248-c645e05445a1
      iscommand: false
      name: Fail message
      script: PrintErrorEntry
      type: regular
      version: -1
    taskid: 3b5432ce-c08c-4bfa-8248-c645e05445a1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 890,
          "y": 1335
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      description:
        simple: Installing Software Version ${inputs.target_version}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: c9ad4933-a733-4679-800b-7bdb9832e8be
      iscommand: true
      name: Set Status
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: c9ad4933-a733-4679-800b-7bdb9832e8be
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 40
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      description:
        simple: Software Install failed.
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 02cda7ed-82a7-4b7a-8d8e-d22d43f8b744
      iscommand: true
      name: Set Description
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 02cda7ed-82a7-4b7a-8d8e-d22d43f8b744
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 890,
          "y": 1160
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1510,
        "width": 820,
        "x": 450,
        "y": -80
      }
    }
  }
