description: Checks a specific version of software for any open CVEs, and if they
  exist, starts a domain upgrade for that system to a fixed version.
id: PAN-OS Network Operations - Check Version for CVEs
inputs:
- description: Software version to check.
  key: panos_version
  playbookInputQuery: null
  required: true
  value: {}
- description: Minimum CVSS score to initiate the upgrade process.
  key: minimum_cvss_score
  playbookInputQuery: null
  required: false
  value:
    simple: "7.0"
name: PAN-OS Network Operations - Check Version for CVEs
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 952d90d6-305b-4a51-8edc-384df79af213
      iscommand: false
      name: ""
      version: -1
    taskid: 952d90d6-305b-4a51-8edc-384df79af213
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 460,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      product:
        simple: PAN-OS
      q:
        simple: ${inputs.panos_version}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets all the advisories for the given product.
      id: 6d5afadd-d289-488f-8af7-1231f562bc81
      iscommand: true
      name: Get the advisories for this Version
      script: '|||pan-advisories-get-advisories'
      type: regular
      version: -1
    taskid: 6d5afadd-d289-488f-8af7-1231f562bc81
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 190
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      advisories:
        simple: ${PANSecurityAdvisory.Advisory}
      version:
        simple: ${inputs.panos_version}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Checks if the given PAN-OS version number is affected by the given
        list of vulnerabilties. '
      id: f3c96297-a8e2-464b-84d4-49925df80c39
      iscommand: false
      name: Check if this version is affected by any CVEs
      script: CheckPanosVersionAffected
      type: regular
      version: -1
    taskid: f3c96297-a8e2-464b-84d4-49925df80c39
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 350
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: cve_id
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: MatchingSecurityAdvisory.cvss_score
                    operator: greaterThan
                    right:
                      iscontext: true
                      value:
                        simple: inputs.minimum_cvss_score
                root: MatchingSecurityAdvisory
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9b2b7658-4c34-4ef5-8b3a-80c9dcec72f3
      iscommand: false
      name: Any matches?
      type: condition
      version: -1
    taskid: 9b2b7658-4c34-4ef5-8b3a-80c9dcec72f3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 460,
          "y": 540
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 39b6d86d-3eda-4e20-81f1-c1b0849e0d1f
      iscommand: false
      name: Finish
      type: title
      version: -1
    taskid: 39b6d86d-3eda-4e20-81f1-c1b0849e0d1f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 470,
          "y": 1090
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      description:
        complex:
          accessor: cve_id
          filters:
          - - left:
                iscontext: true
                value:
                  simple: MatchingSecurityAdvisory.cvss_score
              operator: greaterThanOrEqual
              right:
                iscontext: true
                value:
                  simple: inputs.minimum_cvss_score
          root: MatchingSecurityAdvisory
          transformers:
          - args:
              separator:
                value:
                  simple: ', '
            operator: join
          - args:
              prefix:
                value:
                  simple: |+
                    This version is affected by the following CVEs:

              suffix:
                value:
                  simple: |2-


                    This incident will upgrade all the devices on this version to a fixed release.
            operator: concat
      name:
        simple: Automatic CVE Remedation Upgrade - ${inputs.panos_version}
      panosnetworkoperationsdeviceupgradequery:
        simple: panosnetworkoperationsrunningsoftwareversion:${inputs.panos_version}
      panosnetworkoperationsparentincidentid:
        simple: ${incident.id}
      type:
        simple: PAN-OS Network Operations - Batch Upgrade
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.create.inc
      id: 259d3f73-e45c-4dd3-84e9-e287e1fd9e7c
      iscommand: true
      name: Create Platform Upgrade Incident
      script: Builtin|||createNewIncident
      type: regular
      version: -1
    taskid: 259d3f73-e45c-4dd3-84e9-e287e1fd9e7c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 470,
          "y": 910
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1105,
        "width": 390,
        "x": 460,
        "y": 50
      }
    }
  }
