description: Onboards the NGFW and Panorama devices as XSOAR incidents.
id: PAN-OS Network Operations - Onboarding
inputs: []
name: PAN-OS Network Operations - Onboarding
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 29bd1893-c8f8-4d69-88e7-5ed0c87420c9
      iscommand: false
      name: ""
      version: -1
    taskid: 29bd1893-c8f8-4d69-88e7-5ed0c87420c9
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      target:
        simple: ${PANOS.ShowSystemInfo.Summary.hostid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Given a target device, creates or updates an existing PAN-OS Network
        Operations - Device incident.
      id: 5a1378aa-2349-4aa7-81c5-40bb2a7269f7
      iscommand: false
      name: Update device incidents
      script: CreateOrUpdateDeviceIncident
      type: regular
      version: -1
    taskid: 5a1378aa-2349-4aa7-81c5-40bb2a7269f7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets information from all PAN-OS systems in the topology.
      id: 9ba5364a-1c9c-41e6-88c1-ca0da54e0466
      iscommand: true
      name: Get system information
      script: '|||pan-os-platform-get-system-info'
      type: regular
      version: -1
    taskid: 9ba5364a-1c9c-41e6-88c1-ca0da54e0466
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      linkedIncidentIDs:
        simple: ${DeviceIncidents.device_incident_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.linkIncidents
      id: 15da275f-ae3c-4baf-821f-9dfd0da95f86
      iscommand: true
      name: Link Incidents
      script: Builtin|||linkIncidents
      type: regular
      version: -1
    taskid: 15da275f-ae3c-4baf-821f-9dfd0da95f86
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 530
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 225785dd-8fae-45d7-86eb-4ce84a771b30
      iscommand: false
      name: Onboarding Finished
      type: title
      version: -1
    taskid: 225785dd-8fae-45d7-86eb-4ce84a771b30
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 710
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 725,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
