description: Upgrades a single or HA pair of PAN-OS firewalls.
id: PAN-OS Network Operations - Device Upgrade
inputs:
- description: Target Firewall for upgrade
  key: target_device
  playbookInputQuery: null
  required: false
  value:
    simple: ${incident.panosnetworkoperationstarget}
- description: Peer firewall (if any)
  key: peer_device
  playbookInputQuery: null
  required: false
  value:
    simple: ${incident.panosnetworkoperationsupgradepeerfirewall}
- description: Target version of upgrade
  key: target_version
  playbookInputQuery: null
  required: false
  value:
    simple: ${incident.panosnetworkoperationsupgradetargetversion}
name: PAN-OS Network Operations - Device Upgrade
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "58"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7c1883ec-e2e6-456c-8eae-b6673e0348d2
      iscommand: false
      name: ""
      version: -1
    taskid: 7c1883ec-e2e6-456c-8eae-b6673e0348d2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 520,
          "y": -3250
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: ba4069c4-aad7-41ee-8f60-fc0fbc2e61b2
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: ba4069c4-aad7-41ee-8f60-fc0fbc2e61b2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 840,
          "y": -3090
        }
      }
  "40":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.panosnetworkoperationsparentincidentid
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "40"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "59"
      "yes":
      - "41"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: True if this incident was created by another incident.
      id: 612cec0e-c26a-4662-8d11-d78c0f64142f
      iscommand: false
      name: Do we have a parent incident?
      type: condition
      version: -1
    taskid: 612cec0e-c26a-4662-8d11-d78c0f64142f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 520,
          "y": -2550
        }
      }
  "41":
    continueonerrortype: ""
    id: "41"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "59"
    note: false
    quietmode: 0
    scriptarguments:
      linkedIncidentIDs:
        simple: ${incident.panosnetworkoperationsparentincidentid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.linkIncidents
      id: 0ef79008-e369-4166-82e3-b2ce48f54f0c
      iscommand: true
      name: Link to parent
      script: Builtin|||linkIncidents
      type: regular
      version: -1
    taskid: 0ef79008-e369-4166-82e3-b2ce48f54f0c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 750,
          "y": -2350
        }
      }
  "48":
    continueonerrortype: ""
    id: "48"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "40"
    note: false
    quietmode: 0
    scriptarguments:
      description:
        simple: Awaiting Upgrade Confirmation
      name:
        simple: PAN-OS Upgrade - ${inputs.target_device}
      severity:
        simple: "0.5"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 81ce5b36-8a0d-4ab6-82ed-c3cb3fbad103
      iscommand: true
      name: Set Status
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 81ce5b36-8a0d-4ab6-82ed-c3cb3fbad103
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 520,
          "y": -2755
        }
      }
  "58":
    continueonerrortype: ""
    id: "58"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "48"
    note: false
    quietmode: 0
    scriptarguments:
      incidentId:
        simple: ${incident.id}
      value:
        simple: ${inputs.target_device}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Associates the device indicator to this incident; required when
        this is run as part of a batch upgrade
      id: 281bc03a-ef20-4914-8ebf-01500ab2c0db
      iscommand: true
      name: Associate Device Indicator to this Incident
      script: Builtin|||associateIndicatorToIncident
      type: regular
      version: -1
    taskid: 281bc03a-ef20-4914-8ebf-01500ab2c0db
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 520,
          "y": -2920
        }
      }
  "59":
    continueonerrortype: ""
    id: "59"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "62"
    note: false
    quietmode: 0
    scriptarguments:
      target:
        simple: ${inputs.target_device}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Requests the available software images from a firewall, filters
        them, then prompts the user to select the version.
      id: d2acdb39-9077-46a5-8af4-22902f8d35b0
      iscommand: false
      name: PAN-OS Network Operations - Filter and Select Available Software Images
      playbookId: e68255ec-01a8-40a5-82d4-93b104eeb851
      type: playbook
      version: -1
    taskid: d2acdb39-9077-46a5-8af4-22902f8d35b0
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 520,
          "y": -2140
        }
      }
  "61":
    continueonerrortype: ""
    id: "61"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9f47681d-9ca5-43c9-8d8c-502840609773
      iscommand: false
      name: Complete!
      type: title
      version: -1
    taskid: 9f47681d-9ca5-43c9-8d8c-502840609773
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 520,
          "y": -1790
        }
      }
  "62":
    continueonerrortype: ""
    id: "62"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "61"
    note: false
    quietmode: 0
    scriptarguments:
      peer_device:
        simple: ${incident.panosnetworkoperationsupgradepeerfirewall}
      target_device:
        simple: ${incident.panosnetworkoperationstarget}
      target_version:
        simple: ${incident.upgradepath}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 6489a882-d48d-463a-8158-702c8e3a5fa0
      iscommand: false
      name: PAN-OS Network Operations - Device Upgrade Loop
      playbookId: bdf72993-9e2c-424d-855a-ab69079b1d3a
      type: playbook
      version: -1
    taskid: 6489a882-d48d-463a-8158-702c8e3a5fa0
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 520,
          "y": -1970
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1525,
        "width": 700,
        "x": 520,
        "y": -3250
      }
    }
  }
