description: Download PAN-OS System software.
id: PAN-OS Network Operations - Download Software
inputs:
- description: Target Firewall - Serial or IP address
  key: target
  playbookInputQuery: null
  required: false
  value: {}
- description: Target Software Version to Download
  key: target_version
  playbookInputQuery: null
  required: false
  value: {}
- description: Default max timeout value
  key: timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "45"
name: PAN-OS Network Operations - Download Software
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0127f010-a412-4def-89ed-386906b36c73
      iscommand: false
      name: ""
      version: -1
    taskid: 0127f010-a412-4def-89ed-386906b36c73
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 440,
          "y": -510
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      retry-count:
        simple: "5"
      retry-interval:
        simple: "60"
      version:
        simple: ${inputs.target_version}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Download The provided software version onto the device.
      id: 9b009878-e1d6-4ea1-87fa-38280f3063c7
      iscommand: true
      name: Download the Software Version
      script: '|||pan-os-platform-download-software'
      type: regular
      version: -1
    taskid: 9b009878-e1d6-4ea1-87fa-38280f3063c7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": -225
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      device_filter_string:
        simple: ${PANOS.DownloadStatus.Summary.hostid}
      ignore-outputs:
        simple: "false"
      job_type:
        simple: Downld
      status:
        simple: ACT
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get all the jobs from the devices in the environment.
      id: 3231f280-70d0-4582-8db7-e3d845784fec
      iscommand: true
      name: Get Jobs
      script: '|||pan-os-platform-get-jobs'
      type: regular
      version: -1
    taskid: 3231f280-70d0-4582-8db7-e3d845784fec
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": -50
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      scriptArguments:
        Ids:
          complex:
            accessor: id
            root: PANOS.JobStatus
            transformers:
            - operator: LastArrayElement
        Interval:
          simple: "1"
        PollingCommandArgName:
          simple: id
        PollingCommandName:
          simple: pan-os-platform-get-jobs
        Timeout:
          simple: "30"
        dt:
          simple: PANOS.JobStatus(val.status!=="FIN").id
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: device_filter_string
      AdditionalPollingCommandArgValues:
        simple: ${inputs.target}
      Ids:
        complex:
          accessor: id
          root: PANOS.JobStatus
          transformers:
          - operator: LastArrayElement
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: id
      PollingCommandName:
        simple: pan-os-platform-get-jobs
      Timeout:
        simple: ${inputs.timeout}
      dt:
        simple: PANOS.JobStatus(val.status!=="FIN").id
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: d40a3de8-0b96-4cc1-867b-ef199661da6a
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: d40a3de8-0b96-4cc1-867b-ef199661da6a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 440,
          "y": 670
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        complex:
          accessor: id
          root: PANOS.JobStatus
          transformers:
          - operator: LastArrayElement
      target:
        simple: ${inputs.target}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get all the jobs from the devices in the environment, or a single
        job when ID is specified.
      id: c3a19b94-0724-4354-8f95-6a39e4f05449
      iscommand: true
      name: Get jobs again to check status
      script: '|||pan-os-platform-get-jobs'
      type: regular
      version: -1
    taskid: c3a19b94-0724-4354-8f95-6a39e4f05449
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 820
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PANOS.JobStatus.status
          operator: isEqualString
          right:
            value:
              simple: FIN
      - - left:
            iscontext: true
            value:
              simple: PANOS.JobStatus.result
          operator: isEqualString
          right:
            value:
              simple: OK
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: True if the software download was successful
      id: 834d7310-2fa6-4aa9-8be2-ba2fc9d66f9e
      iscommand: false
      name: Did it complete?
      type: condition
      version: -1
    taskid: 834d7310-2fa6-4aa9-8be2-ba2fc9d66f9e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 440,
          "y": 990
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 291d608b-528b-440c-8d60-b302f0edf4c5
      iscommand: false
      name: Finish
      type: title
      version: -1
    taskid: 291d608b-528b-440c-8d60-b302f0edf4c5
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1180
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: Download job failed.
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints an error entry with a given message
      id: 8a289227-b274-4d2a-8311-c61d44b31ecd
      iscommand: false
      name: Fail message
      script: PrintErrorEntry
      type: regular
      version: -1
    taskid: 8a289227-b274-4d2a-8311-c61d44b31ecd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 870,
          "y": 1165
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      description:
        simple: Downloading Software Version ${inputs.target_version}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 5ce4bf6e-a115-4a02-8409-dcbb17833aaa
      iscommand: true
      name: Set Status
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 5ce4bf6e-a115-4a02-8409-dcbb17833aaa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": -390
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "30"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: d8d5acfe-5554-4011-878e-b02713112343
      iscommand: false
      name: Wait for job to get processed
      script: Sleep
      type: regular
      version: -1
    taskid: d8d5acfe-5554-4011-878e-b02713112343
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 320
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PANOS.JobStatus.id
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 05c34781-a28c-4e70-8b5f-c39b4bcfe4ef
      iscommand: false
      name: Did we get a job?
      type: condition
      version: -1
    taskid: 05c34781-a28c-4e70-8b5f-c39b4bcfe4ef
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 440,
          "y": 130
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      device_filter_string:
        simple: ${PANOS.DownloadStatus.Summary.hostid}
      ignore-outputs:
        simple: "false"
      job_type:
        simple: Downld
      status:
        simple: ACT
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get all the jobs from the devices in the environment.
      id: d5042b42-d433-486f-8259-2749425817a2
      iscommand: true
      name: Get Jobs
      script: '|||pan-os-platform-get-jobs'
      type: regular
      version: -1
    taskid: d5042b42-d433-486f-8259-2749425817a2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 490
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1770,
        "width": 850,
        "x": 440,
        "y": -510
      }
    }
  }
