description: Takes a JSON snapshot of the current operational state of the device.
id: be9dfaa4-a371-4b46-8088-67679944a38b
inputs:
- description: The target to take the snapshot of
  key: target
  playbookInputQuery: null
  required: true
  value:
    simple: ${incident.panosnetworkoperationstarget}
name: PAN-OS Network Operations - Take Snapshot
outputs:
- contextPath: File.EntryID
  description: The file entry ID.
  type: string
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d971ca3e-bc87-4864-87dc-d6ba79efc4fd
      iscommand: false
      name: ""
      version: -1
    taskid: d971ca3e-bc87-4864-87dc-d6ba79efc4fd
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: true
    quietmode: 0
    scriptarguments:
      target:
        simple: ${inputs.target}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Takes a JSON Snapshot of the current operational state of the target
        device
      id: 7830597e-45ba-4058-841e-1126b376f26c
      iscommand: false
      name: Take Snapshot
      script: TakeOperationalSnapshot
      tags:
      - snapshot-file
      type: regular
      version: -1
    taskid: 7830597e-45ba-4058-841e-1126b376f26c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1576eda4-4445-4dd7-8a15-2c3706dd0fe2
      iscommand: false
      name: Finish
      type: title
      version: -1
    taskid: 1576eda4-4445-4dd7-8a15-2c3706dd0fe2
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 570
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      description:
        simple: Taking System Snapshot
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: d9dad543-1d0d-4b51-8541-2915d5bb2e0b
      iscommand: true
      name: Set Status
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: d9dad543-1d0d-4b51-8541-2915d5bb2e0b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 585,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
