description: 'This playbook registers a firewall - based on a provided target IP -
  in Panorama. It adds the firewall to the support portal, ensures the licenses are
  retrieved and finally configures it so it can talk to Panorama. '
id: 82aae2be-6e47-4aa7-8eb8-47508990e6ae
inputs:
- description: The IP address of the firewall to be onboarded.
  key: target_ip
  playbookInputQuery: null
  required: true
  value:
    simple: ${incident.currentipaddress}
- description: This is the admin password that will be set as the first changed password.
    The admin password can - and should - be changed after onboarding by pushing the
    actual password via a Panorama template.
  key: new_admin_password
  playbookInputQuery: null
  required: true
  value:
    simple: TestPassword!
- description: ""
  key: panorama_ip
  playbookInputQuery: null
  required: false
  value:
    simple: 192.168.1.145
- description: ""
  key: backup_panorama_ip
  playbookInputQuery: null
  required: false
  value:
    simple: ${incident.targetbackuppanoramaserver}
- description: ""
  key: device_group
  playbookInputQuery: null
  required: false
  value:
    simple: ${incident.onboardtodevicegroup}
- description: ""
  key: template_stack
  playbookInputQuery: null
  required: false
  value:
    simple: ${incident.onboardtotemplatestack}
- description: The name of the Deployment key to use for all onboarded devices (10.1+)
  key: deployment_key_name
  playbookInputQuery: null
  required: false
  value:
    simple: depoyment_key
name: PAN-OS Network Operations - Onboard Firewall
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 887c33f1-00bf-4df5-8b5a-4354b4aade64
      iscommand: false
      name: ""
      version: -1
    taskid: 887c33f1-00bf-4df5-8b5a-4354b4aade64
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -370
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      hostname:
        simple: ${inputs.target_ip}
      new_admin_password:
        simple: ${inputs.new_admin_password}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Performs the very first login to PAN-OS NGFW that is currently
        expecting the username and password to be changed.
      id: dec2dfbb-febf-490f-81f4-e722caea9b5c
      iscommand: false
      name: Setup the Firewall over SSH
      script: SetupFirewallFirstLogin
      type: regular
      version: -1
    taskid: dec2dfbb-febf-490f-81f4-e722caea9b5c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 500
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4f783626-23be-424e-8364-78ac5d40d96d
      iscommand: false
      name: Configure the Firewall
      type: title
      version: -1
    taskid: 4f783626-23be-424e-8364-78ac5d40d96d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      backup_panorama_ip:
        simple: ${inputs.backup_panorama_ip}
      device_auth_key:
        simple: ${authkey.response.result.authkey.entry.key}
      hostname:
        simple: ${inputs.target_ip}
      new_hostname:
        simple: ${incident.newhostname}
      panorama_ip:
        simple: ${inputs.panorama_ip}
      password:
        simple: ${inputs.new_admin_password}
      use_dhcp_for_management:
        simple: "Yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Configures the firewall to point to Panorama and commits the configuraiton.
      id: eef6c623-658c-4b70-825d-717317c478e2
      iscommand: false
      name: Configures the System Settings of the firewall
      script: SetupFirewallForOnboarding
      type: regular
      version: -1
    taskid: eef6c623-658c-4b70-825d-717317c478e2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 820
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      onboardingstatus:
        simple: Performing First Login
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 94d6914a-e2ce-4183-87c9-29ac8b351dad
      iscommand: true
      name: Set Status
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 94d6914a-e2ce-4183-87c9-29ac8b351dad
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 330
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      onboardingstatus:
        simple: Configuring Panorama
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 7e0f32c9-ec2c-43ee-843d-22dc2d6fc1e0
      iscommand: true
      name: Set Status
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 7e0f32c9-ec2c-43ee-843d-22dc2d6fc1e0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 660
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7758912c-1209-47e5-8251-3fe397add410
      iscommand: false
      name: Add Device to Panorama
      type: title
      version: -1
    taskid: 7758912c-1209-47e5-8251-3fe397add410
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 980
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      onboardingstatus:
        simple: Adding Device to Panorama
      serialnumber:
        simple: ${SetupFirewallForOnboarding.serial}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 7d821863-84f6-4547-841b-dda813e27f1f
      iscommand: true
      name: Set Status
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 7d821863-84f6-4547-841b-dda813e27f1f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1110
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      cmd:
        simple: <request><authkey><add><devtype>fw</devtype><serial><member>${SetupFirewallForOnboarding.serial}</member></serial><name>${inputs.deployment_key_name}</name><lifetime>6000</lifetime><count>10</count></add></authkey></request>
      is_xml:
        simple: "true"
      type:
        simple: op
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Adds the auth key to the firewall. Skipped if Running < 10.1.2
        software.
      id: 240d819f-26af-4926-8d47-c7e1b7693ff2
      iscommand: true
      name: Add the firewall serial number to the deployment key list of serials
      script: '|||pan-os'
      type: regular
      version: -1
    taskid: 240d819f-26af-4926-8d47-c7e1b7693ff2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1280
        }
      }
  "9":
    continueonerror: true
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      cmd:
        simple: <request><authkey><list>depoyment_key</list></authkey></request>
      extend-context:
        simple: authkey=.
      type:
        simple: op
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Retrieves the device deployment key, if there is one. '
      id: d268d3ba-489e-4f6c-8223-baaac14afc9b
      iscommand: true
      name: Get the device deployment key
      script: '|||pan-os'
      type: regular
      version: -1
    taskid: d268d3ba-489e-4f6c-8223-baaac14afc9b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -20
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: set
      element:
        simple: <entry name='${SetupFirewallForOnboarding.serial}'/>
      type:
        simple: config
      xpath:
        simple: /config/mgt-config/devices
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Runs any command supported in the API.
      id: 8776ca6e-3630-48a9-8f3b-c6d4f5347e99
      iscommand: true
      name: Add to the list of managed devices
      script: '|||pan-os'
      type: regular
      version: -1
    taskid: 8776ca6e-3630-48a9-8f3b-c6d4f5347e99
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1460
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: set
      element:
        simple: <entry name='${SetupFirewallForOnboarding.serial}'/>
      type:
        simple: config
      xpath:
        simple: /config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='${inputs.template_stack}']/devices
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Runs any command supported in the API.
      id: 29243141-a4c0-4d5d-8d75-b75a64e0c9e7
      iscommand: true
      name: Add to the Template-Stack
      script: '|||pan-os'
      type: regular
      version: -1
    taskid: 29243141-a4c0-4d5d-8d75-b75a64e0c9e7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 240,
          "y": 1630
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: set
      element:
        simple: <entry name='${SetupFirewallForOnboarding.serial}'/>
      type:
        simple: config
      xpath:
        simple: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='${inputs.device_group}']/devices
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Runs any command supported in the API.
      id: e394077e-a75d-4089-8090-9d8ef37934ac
      iscommand: true
      name: Add to the device-group
      script: '|||pan-os'
      type: regular
      version: -1
    taskid: e394077e-a75d-4089-8090-9d8ef37934ac
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 660,
          "y": 1630
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      onboardingstatus:
        simple: Committing Configuration
      panoramaserveradded:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 741ce6c7-0cdc-48a8-8aea-e8d949248b64
      iscommand: true
      name: Set Status
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 741ce6c7-0cdc-48a8-8aea-e8d949248b64
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1810
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      polling:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Commits a configuration to the Palo Alto firewall or Panorama,
        validates if a commit was successful if using polling="true" otherwise does
        not validate if the commit was successful. Committing to Panorama does not
        push the configuration to the firewalls. To push the configuration, run the
        panorama-push-to-device-group command.
      id: 2734d7b7-c590-4c59-836c-931cc667773c
      iscommand: true
      name: Commit to Panorama
      script: '|||pan-os-commit'
      type: regular
      version: -1
    taskid: 2734d7b7-c590-4c59-836c-931cc667773c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1980
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      onboardingstatus:
        simple: Waiting for Panorama Connection
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 94bb31b0-01df-469f-8b06-a62b1cf881e7
      iscommand: true
      name: Set Status
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 94bb31b0-01df-469f-8b06-a62b1cf881e7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2150
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 74378b3b-6480-457d-87d5-2fd4edf02105
      iscommand: false
      name: Start the Onboarding Timer
      type: title
      version: -1
    taskid: 74378b3b-6480-457d-87d5-2fd4edf02105
    timertriggers:
    - action: start
      fieldname: pauseforpanorama
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2310
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8008031e-f822-4dda-8a43-9aa7e31ac4f2
      iscommand: false
      name: Start Onboarding
      type: title
      version: -1
    taskid: 8008031e-f822-4dda-8a43-9aa7e31ac4f2
    timertriggers:
    - action: start
      fieldname: onboardingtime
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": -200
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2745,
        "width": 800,
        "x": 240,
        "y": -370
      }
    }
  }
