description: Given a PAN-OS version, searches the security advisories website for
  matching CVEs and relates them when seen.
id: 1e9d1015-078f-4ac0-8bf7-6a471404561d
inputs:
- description: ""
  key: panos_version
  playbookInputQuery: null
  required: false
  value:
    simple: 9.0.5
- description: ""
  key: panos_id
  playbookInputQuery: null
  required: false
  value:
    simple: 6F5A32602DF9260
- description: ""
  key: device_type
  playbookInputQuery: null
  required: false
  value:
    simple: Network Device
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: type:"Panorama Device" or type:"Network Device"
    queryEntity: indicators
    results: null
    runFromLastJobTime: true
  required: false
  value: {}
name: PAN-OS Network Operations - Create CVE Relationships
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d54ccaf4-914e-4c89-8829-d64c1c5afd95
      iscommand: false
      name: ""
      version: -1
    taskid: d54ccaf4-914e-4c89-8829-d64c1c5afd95
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -640
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      product:
        simple: PAN-OS
      q:
        simple: ${inputs.panos_version}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets all the advisories for the given product.
      id: 14c2472b-a502-4fa0-8a36-3c5d6eadbc52
      iscommand: true
      name: Get the advisories for this Version
      script: '|||pan-advisories-get-advisories'
      type: regular
      version: -1
    taskid: 14c2472b-a502-4fa0-8a36-3c5d6eadbc52
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -310
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      advisories:
        simple: ${PANSecurityAdvisory.Advisory}
      version:
        simple: ${inputs.panos_version}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the given PAN-OS version number is affected by the given
        list of vulnerabilties from the pan-advisories-get-advisories command.
      id: 89094a11-1195-48a0-8c05-da334859a387
      iscommand: false
      name: Check if this version is affected by any CVEs
      script: CheckPanosVersionAffected
      type: regular
      version: -1
    taskid: 89094a11-1195-48a0-8c05-da334859a387
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 30
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      entities_types:
        simple: CVE
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This automation outputs the indicator relationships to context
        according to the provided query, using the entities, entityTypes, and relationships
        arguments. All arguments will use the AND operator. For example, using the
        following arguments entities=8.8.8.8 entities_types=Domain will provide only
        relationships that the 8.8.8.8 indicator has with indicators of type domain.
      id: 4bab18ee-4262-4459-8cc4-3f2926fdab1f
      iscommand: false
      name: Find Existing Relationships
      script: SearchIndicatorRelationships
      type: regular
      version: -1
    taskid: 4bab18ee-4262-4459-8cc4-3f2926fdab1f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -490
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      ids:
        complex:
          accessor: ID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Relationships.EntityB
              operator: notIn
              right:
                iscontext: true
                value:
                  simple: MatchingSecurityAdvisory.cve_id
          root: Relationships
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This automation allows to delete a relationship between indicator
        objects based on the relationship id.
      id: 4eec38a1-0063-475a-8469-df286309a3de
      iscommand: false
      name: Delete any CVE Relationships no longer applicable to this version.
      script: DeleteIndicatorRelationships
      type: regular
      version: -1
    taskid: 4eec38a1-0063-475a-8469-df286309a3de
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 790
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      entity_a:
        simple: ${inputs.panos_id}
      entity_a_type:
        simple: Network Device
      entity_b:
        simple: ${MatchingSecurityAdvisory.cve_id}
      entity_b_type:
        simple: CVE
      relationship:
        simple: related-to
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This automation creates a relationship between indicator objects.
      id: b6e43fb7-360d-4249-8eb1-50cb227ae5d4
      iscommand: false
      name: Create Indicator Relationships
      script: CreateIndicatorRelationship
      type: regular
      version: -1
    taskid: b6e43fb7-360d-4249-8eb1-50cb227ae5d4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 450
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: ID
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: Relationships.EntityB
                    operator: notIn
                    right:
                      iscontext: true
                      value:
                        simple: MatchingSecurityAdvisory.cve_id
                root: Relationships
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b1edcb66-8001-4212-89a4-b3c94f3b6006
      iscommand: false
      name: Are there now redundant relationships?
      type: condition
      version: -1
    taskid: b1edcb66-8001-4212-89a4-b3c94f3b6006
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 615
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 77b65b33-5c17-45bb-80a2-7dc50faefb07
      iscommand: false
      name: Finish
      type: title
      version: -1
    taskid: 77b65b33-5c17-45bb-80a2-7dc50faefb07
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 970
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PANSecurityAdvisory.Advisory.cve_id
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ba617f5f-8de2-4353-87ea-dd9670f93e07
      iscommand: false
      name: Did we get any advisories?
      type: condition
      version: -1
    taskid: ba617f5f-8de2-4353-87ea-dd9670f93e07
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": -150
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      ids:
        simple: ${Relationships.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This automation allows to delete a relationship between indicator
        objects based on the relationship id.
      id: 7f445b0f-c270-4e5d-89f7-3ea192684ef2
      iscommand: false
      name: Delete all CVE Relationships.
      script: DeleteIndicatorRelationships
      type: regular
      version: -1
    taskid: 7f445b0f-c270-4e5d-89f7-3ea192684ef2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 800
        }
      }
  "10":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: MatchingSecurityAdvisory.cve_id
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7a51a16b-1ba5-4172-8dd4-238a45a9b4fb
      iscommand: false
      name: Did we get any advisories?
      type: condition
      version: -1
    taskid: 7a51a16b-1ba5-4172-8dd4-238a45a9b4fb
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1675,
        "width": 840,
        "x": 450,
        "y": -640
      }
    }
  }
