description: Checks to see if this incident has a parent incident and if so, links
  the two incidents.
id: PAN-OS Network Operations - Incident Callback
inputs: []
name: PAN-OS Network Operations - Incident Callback
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9ab29b95-08c2-42b4-85bd-a06e98657ad1
      iscommand: false
      name: ""
      version: -1
    taskid: 9ab29b95-08c2-42b4-85bd-a06e98657ad1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 20
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${incident.panosnetworkoperationsclosetaskid}
      incidentId:
        simple: ${incident.panosnetworkoperationsparentincidentid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.task.complete
      id: 765889df-b411-4873-89bf-e13598f42f30
      iscommand: true
      name: Mark Complete
      script: Builtin|||taskComplete
      type: regular
      version: -1
    taskid: 765889df-b411-4873-89bf-e13598f42f30
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 330
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4a0926af-7014-4ac4-898b-7f0eb68f6088
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 4a0926af-7014-4ac4-898b-7f0eb68f6088
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 490
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.panosnetworkoperationsclosetaskid
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Chefcks if the incident callback needs to run.
      id: ea5b9370-700a-476a-89a2-3916cba9e541
      iscommand: false
      name: Do we have a parent task to mark complete?
      type: condition
      version: -1
    taskid: ea5b9370-700a-476a-89a2-3916cba9e541
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 150
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 535,
        "width": 380,
        "x": 450,
        "y": 20
      }
    }
  }
