description: This playbook runs the fixes identified by GroupIssuesByFields as a looped
  playbook to ensure the correct objects are updated at all times.
id: 6abaaf4d-6a84-4f35-8e60-2038625a349a
inputs:
- description: ""
  key: issue_to_fix
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: new_value
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: object_type
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: attribute_to_update
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: device
  playbookInputQuery: null
  required: false
  value:
    simple: ${incident.panosnetworkoperationstarget}
name: PAN-OS Network Operations - Run Bulk Change
outputs:
- contextPath: PANOS.PanosUpdatedObject
  description: Updated Objects.
  type: unknown
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e8b51f2a-52f9-4c36-8bd2-80ca5e92d6eb
      iscommand: false
      name: ""
      version: -1
    taskid: e8b51f2a-52f9-4c36-8bd2-80ca5e92d6eb
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      attribute_to_update:
        simple: ${inputs.attribute_to_update}
      device_filter_string:
        simple: ${inputs.device}
      new_values:
        simple: ${inputs.new_value}
      object_names:
        simple: ${inputs.issue_to_fix.object_names}
      object_type:
        simple: ${inputs.object_type}
      parent:
        simple: ${inputs.issue_to_fix.location}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Updates a single attribute for all the given PAN-OS objects or rules by name. This is a potentially disruptive command
        as it will replace all objects of the same type and parent in the XML tree.
      id: 332f97bd-7384-4f6e-8b68-158960aaa894
      iscommand: true
      name: Execute The Change
      script: '|||pan-os-config-bulk-update-objects'
      type: regular
      version: -1
    taskid: 332f97bd-7384-4f6e-8b68-158960aaa894
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 232b659d-ac60-4eed-8257-b863b643ca04
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 232b659d-ac60-4eed-8257-b863b643ca04
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 395,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
