name: Releases

on:
  push:
    tags:
    - '*'

jobs:

  zip_and_release:
    env:
      PYTHON_RELEASE_VERSION: 3.10
      PACK_NAME: PAN_OS_Upgrade_Services

    name: "Package ZIP And upload as release."
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: "Set up Python $PYTHON_RELEASE_VERSION"
      uses: actions/setup-python@v4
      with:
        python-version: "$PYTHON_RELEASE_VERSION"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest demisto-sdk
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create content zip
      run: |
        demisto-sdk zip-packs -i Packs/$PACK_NAME/ -o /tmp
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "/tmp/uploadable_packs/$PACK_NAME"
        bodyFile: "release.md"