name: Releases

on:
  push:
    tags:
      - '*'

jobs:

  zip_and_release:
    name: "Package ZIP And upload as release."
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest demisto-sdk
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create content zip
        run: |
          demisto-sdk zip-packs -i Packs/PAN_OS_Upgrade_Services/ -o /tmp
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "/tmp/uploadable_packs/PAN_OS_Upgrade_Services.zip"
          bodyFile: "release.md"